package config

import (
	"os"
	"strings"
	"testing"
)

// Verifies that help text generated from the flag registry includes every
// CLI flag's long name, proving flags and help text share a single source.
func TestFlagUsageContainsAllFlags(t *testing.T) {
	usage := FlagUsage()
	for _, f := range Flags {
		if f.Long == "" {
			continue
		}
		if !strings.Contains(usage, f.Long) {
			t.Errorf("FlagUsage() missing flag %s", f.Long)
		}
	}
}

// Verifies that help text includes the default value from each FlagDef.
func TestFlagUsageContainsDefaults(t *testing.T) {
	usage := FlagUsage()
	for _, f := range Flags {
		if f.Default == "" || f.Long == "" {
			continue
		}
		expected := "default: " + f.Default
		if !strings.Contains(usage, expected) {
			t.Errorf("FlagUsage() for %s missing %q", f.Long, expected)
		}
	}
}

// Verifies that help text includes env var names for flags that appear in CLI help.
// Config-only flags (Long == "") are excluded since they don't appear in help output.
func TestFlagUsageContainsEnvVars(t *testing.T) {
	usage := FlagUsage()
	for _, f := range Flags {
		if f.EnvVar == "" || f.Long == "" {
			continue
		}
		if !strings.Contains(usage, f.EnvVar) {
			t.Errorf("FlagUsage() missing env var %s for flag %s", f.EnvVar, f.Long)
		}
	}
}

// Verifies that every CLI flag in the registry is recognized by Parse(),
// ensuring the registry and parser are in sync.
func TestAllRegisteredFlagsAreParseable(t *testing.T) {
	t.Setenv("RALPH_MAX_ITERATIONS", "")
	t.Setenv("RALPH_IDLE_TIMEOUT", "")
	t.Setenv("RALPH_IDLE_TIMEOUT_PROGRESS", "")
	t.Setenv("RALPH_BASE_BRANCH", "")


	for _, f := range Flags {
		if f.Long == "" && f.Short == "" {
			continue
		}
		if f.Long == "--help" {
			continue
		}

		name := f.Long
		if name == "" {
			name = f.Short
		}

		var args []string
		args = append(args, name)
		if f.Kind != KindBool {
			switch f.Kind {
			case KindInt:
				args = append(args, "42")
			case KindString:
				args = append(args, "test")
			case KindDuration:
				args = append(args, "5m")
			case KindStringList:
				args = append(args, "a,b")
			}
		}

		_, err := Parse(args)
		if err != nil && strings.Contains(err.Error(), "unknown") {
			t.Errorf("Flag %s defined in registry but not recognized by Parse()", name)
		}
	}
}

// Verifies that ralph merge's flags are defined via the shared FlagDef
// mechanism rather than a separate ad-hoc struct: MergeFlags entries parse
// through the same ParseFlags helper Parse() itself uses, --no-ci-wait and
// --admin-merge-on-ci-infra-failure set the expected Config fields, and the
// PR number positional argument is preserved for the caller. This is the
// behavior cmd/ralph's handleMerge relies on for ralph merge <pr> [flags].
func TestMergeFlagsParseViaSharedFlagDefMechanism(t *testing.T) {
	var cfg Config
	positional, err := ParseFlags(MergeFlags, &cfg, []string{"321", "--no-ci-wait", "--admin-merge-on-ci-infra-failure"})
	if err != nil {
		t.Fatalf("ParseFlags(MergeFlags, ...) error: %v", err)
	}
	if len(positional) != 1 || positional[0] != "321" {
		t.Errorf("positional = %v, want [\"321\"]", positional)
	}
	if !cfg.SkipCIWait {
		t.Error("--no-ci-wait should set cfg.SkipCIWait")
	}
	if !cfg.AdminMergeOnCIInfraFailure {
		t.Error("--admin-merge-on-ci-infra-failure should set cfg.AdminMergeOnCIInfraFailure")
	}
}

// Verifies that an unrecognized flag against MergeFlags is rejected, so a
// typo (or a loop-only flag like --tmux) doesn't silently no-op for ralph merge.
func TestMergeFlagsRejectsUnknownFlag(t *testing.T) {
	var cfg Config
	_, err := ParseFlags(MergeFlags, &cfg, []string{"321", "--tmux"})
	if err == nil {
		t.Fatal("expected error for --tmux, which is not a MergeFlags entry")
	}
	if !strings.Contains(err.Error(), "unknown flag") {
		t.Errorf("error should mention 'unknown flag', got %q", err)
	}
}

// Verifies that merge's help text is generated by the same FlagUsageFor path
// used elsewhere, rather than hand-rolled Printf formatting.
func TestFlagUsageForMergeFlagsContainsBothFlags(t *testing.T) {
	usage := FlagUsageFor(MergeFlags)
	for _, name := range []string{"--no-ci-wait", "--admin-merge-on-ci-infra-failure"} {
		if !strings.Contains(usage, name) {
			t.Errorf("FlagUsageFor(MergeFlags) missing %s", name)
		}
	}
}

// Verifies that every flag with a ConfigKey appears in the config map used
// by LoadConfigFile, ensuring config file support stays in sync.
func TestAllConfigKeysInConfigMap(t *testing.T) {
	for _, f := range Flags {
		if f.ConfigKey == "" {
			continue
		}
		if configMap[f.ConfigKey] == nil {
			t.Errorf("ConfigKey %q defined in Flags but missing from configMap", f.ConfigKey)
		}
	}
}

// Verifies that Defaults() produces values matching every FlagDef.Default,
// proving runtime defaults derive from the Flags registry (single source of truth)
// rather than being independently hardcoded.
func TestDefaultsDeriveFromFlagRegistry(t *testing.T) {
	t.Setenv("RALPH_MAX_ITERATIONS", "")
	t.Setenv("RALPH_IDLE_TIMEOUT", "")
	t.Setenv("RALPH_IDLE_TIMEOUT_PROGRESS", "")
	t.Setenv("RALPH_MAX_RUN_DURATION", "")
	t.Setenv("RALPH_BASE_BRANCH", "")


	cfg := Defaults()

	// Build a second config by applying FlagDef defaults directly.
	check := Config{ProjectDir: "."}
	for i := range Flags {
		f := &Flags[i]
		if f.Default != "" && f.Default != "cwd" {
			if err := f.Apply(&check, f.Default); err != nil {
				t.Fatalf("applying default %q for %s: %v", f.Default, f.Long, err)
			}
		}
	}

	if cfg.MaxIterations != check.MaxIterations {
		t.Errorf("MaxIterations: Defaults()=%d, registry=%d", cfg.MaxIterations, check.MaxIterations)
	}
	if cfg.CallsPerHour != check.CallsPerHour {
		t.Errorf("CallsPerHour: Defaults()=%d, registry=%d", cfg.CallsPerHour, check.CallsPerHour)
	}
	if cfg.IdleTimeout != check.IdleTimeout {
		t.Errorf("IdleTimeout: Defaults()=%v, registry=%v", cfg.IdleTimeout, check.IdleTimeout)
	}
	if cfg.IdleTimeoutProgress != check.IdleTimeoutProgress {
		t.Errorf("IdleTimeoutProgress: Defaults()=%v, registry=%v", cfg.IdleTimeoutProgress, check.IdleTimeoutProgress)
	}
	if cfg.MaxRunDuration != check.MaxRunDuration {
		t.Errorf("MaxRunDuration: Defaults()=%v, registry=%v", cfg.MaxRunDuration, check.MaxRunDuration)
	}
	if cfg.BaseBranch != check.BaseBranch {
		t.Errorf("BaseBranch: Defaults()=%q, registry=%q", cfg.BaseBranch, check.BaseBranch)
	}
	if cfg.WatcherInterval != check.WatcherInterval {
		t.Errorf("WatcherInterval: Defaults()=%d, registry=%d", cfg.WatcherInterval, check.WatcherInterval)
	}
	if cfg.StuckThreshold != check.StuckThreshold {
		t.Errorf("StuckThreshold: Defaults()=%d, registry=%d", cfg.StuckThreshold, check.StuckThreshold)
	}
}

// Verifies that InitConfig generates entries for all flags that have non-empty
// defaults, and that reading the generated file back resolves each one to the
// same key. Flags with ConfigKey but no Default (e.g. post_task) are
// intentionally omitted. A dotted ConfigKey ("acceptance.countdown_seconds") is
// written as a table header plus a bare key, so the round-trip through
// LoadConfigFile — not a substring match — is what proves it survives.
func TestInitConfigUsesRegistry(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/config.toml"

	if err := InitConfig(path); err != nil {
		t.Fatalf("InitConfig failed: %v", err)
	}

	cfg := Config{ProjectDir: "."}
	if err := cfg.LoadConfigFile(path); err != nil {
		t.Fatalf("LoadConfigFile on generated file: %v", err)
	}

	for _, f := range Flags {
		if f.ConfigKey == "" {
			continue
		}
		if f.Kind != KindBool && f.Default == "" {
			continue
		}
		if f.Kind == KindBool {
			// Bools are generated as "false", which LoadConfigFile
			// deliberately treats as "leave at default" — nothing to read back.
			continue
		}
		if !cfg.FileSet(f.ConfigKey) {
			t.Errorf("InitConfig output missing key %q", f.ConfigKey)
		}
	}
}

func readFile(path string) ([]byte, error) {
	return os.ReadFile(path)
}
