package loop

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/brokenalarms/ralph/internal/attempts"
	"github.com/brokenalarms/ralph/internal/logging"
	"github.com/brokenalarms/ralph/internal/testutil"
)

// buildPRBody assembles description, acceptance criteria, and agent summary
// into a structured PR body when all context is available.
// buildPRBody is a standalone function — takes backend directly, no Loop needed.
func TestBuildPRBody_FullContext(t *testing.T) {
	backend := &testutil.StubBackend{
		Description: "Fix the auth middleware to validate tokens",
		Acceptance:  "1. Tokens are validated\n2. Invalid tokens return 401",
	}

	body := buildPRBody(backend, "ralph-abc", "Fixed auth middleware token validation")

	if !strings.Contains(body, "## Description") {
		t.Error("body should contain Description section")
	}
	if !strings.Contains(body, "Fix the auth middleware") {
		t.Error("body should contain bead description")
	}
	if !strings.Contains(body, "## Acceptance Criteria") {
		t.Error("body should contain Acceptance Criteria section")
	}
	if !strings.Contains(body, "Tokens are validated") {
		t.Error("body should contain acceptance criteria content")
	}
	if !strings.Contains(body, "## Summary") {
		t.Error("body should contain Summary section")
	}
	if !strings.Contains(body, "Fixed auth middleware") {
		t.Error("body should contain agent summary")
	}
}

func TestBuildPRBody_NoBeadDescription(t *testing.T) {
	backend := &testutil.StubBackend{}

	body := buildPRBody(backend, "ralph-abc", "Implemented the feature")

	if strings.Contains(body, "## Description") {
		t.Error("body should not contain Description when bead has none")
	}
	if !strings.Contains(body, "## Summary") {
		t.Error("body should contain Summary section as fallback")
	}
	if !strings.Contains(body, "Implemented the feature") {
		t.Error("body should contain agent summary")
	}
}

func TestBuildPRBody_NoContext(t *testing.T) {
	backend := &testutil.StubBackend{}

	body := buildPRBody(backend, "", "")

	if body != "" {
		t.Errorf("body should be empty when no context is available, got %q", body)
	}
}

func TestBuildPRBody_NeverGeneric(t *testing.T) {
	backend := &testutil.StubBackend{
		Description: "Some task description",
	}

	body := buildPRBody(backend, "ralph-abc", "completed task")

	if strings.Contains(body, "Automated PR for") {
		t.Error("body must not contain generic 'Automated PR for' text")
	}
	if strings.Contains(body, "Generated by ralph") {
		t.Error("body must not contain generic 'Generated by ralph' text")
	}
}

// finalizePR skips merge and closes the bead when AutoMerge is off.
func TestFinalizePR_NoAutoMerge_ClosesTask(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix auth bug",
		prNumber:  42,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: false,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
	})

	if result.merged {
		t.Error("should not merge when AutoMerge is disabled")
	}
	if !result.closed {
		t.Error("task should be closed even without merge")
	}
	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-abc" {
		t.Errorf("expected CloseTask for ralph-abc, got %v", backend.ClosedIDs)
	}
}

// finalizePR merges and closes when AutoMerge is on and merge succeeds.
func TestFinalizePR_AutoMerge_MergesAndCloses(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	mergeCalled := false
	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-xyz",
		nextTask:  "Add feature",
		prNumber:  42,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			mergeCalled = true
			return true, nil
		},
	})

	if !mergeCalled {
		t.Error("merge should have been called")
	}
	if !result.merged {
		t.Error("should be merged when merge returns true")
	}
	if !result.closed {
		t.Error("task should be closed after merge")
	}
	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-xyz" {
		t.Errorf("expected CloseTask for ralph-xyz, got %v", backend.ClosedIDs)
	}
}

// finalizePR closes the bead (not skips) when merge fails with AutoMerge on.
// Work is verified — it should land in completed_tasks so setStackHead can find
// the branch for the next task to stack on.
func TestFinalizePR_MergeFailure_ClosesTask(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix bug",
		prNumber:  99,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			return false, fmt.Errorf("merge conflict")
		},
	})

	if result.merged {
		t.Error("should not be merged on failure")
	}
	if !result.closed {
		t.Error("task should be closed (not skipped) after merge failure — work is verified")
	}

	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-abc" {
		t.Errorf("expected CloseTask for ralph-abc, got %v", backend.ClosedIDs)
	}
	if len(backend.CloseReasons) == 0 || !strings.Contains(backend.CloseReasons[0], "merge pending") {
		t.Errorf("close reason should indicate merge pending, got %v", backend.CloseReasons)
	}
}

// finalizePR with merge failure records merged:false in completed_tasks so
// setStackHead can find the unmerged branch for the next task to stack on.
func TestFinalizePR_MergeFailure_AppearsInCompletedTasksWithMergedFalse(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix bug",
		prNumber:  99,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			return false, fmt.Errorf("CI check failed")
		},
	})

	tasks, err := st.GetCompletedTasks()
	if err != nil {
		t.Fatalf("GetCompletedTasks: %v", err)
	}
	if len(tasks) != 1 {
		t.Fatalf("expected 1 entry in completed_tasks, got %d", len(tasks))
	}
	if tasks[0].ID != "ralph-abc" {
		t.Errorf("completed task ID = %q, want ralph-abc", tasks[0].ID)
	}
	if tasks[0].Merged {
		t.Error("merged should be false for unmerged PR")
	}
}

// finalizePR with MERGED state closes immediately without attempting merge.
func TestFinalizePR_AlreadyMerged_ClosesImmediately(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-xyz",
		nextTask:  "Add feature",
		prNumber:  42,
		prState:   "MERGED",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			t.Fatal("merge should not be called for already-merged PR")
			return false, nil
		},
	})

	if !result.merged {
		t.Error("should report merged for MERGED state")
	}
	if !result.closed {
		t.Error("task should be closed")
	}
	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-xyz" {
		t.Errorf("expected CloseTask for ralph-xyz, got %v", backend.ClosedIDs)
	}
}

// finalizePR uses PR URL in close reason when available.
func TestFinalizePR_UsesURLInCloseReason(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix login",
		prNumber:  55,
		prState:   "OPEN",
		prURL:     "https://github.com/owner/repo/pull/55",
		workDir:   dir,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
	})

	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.CloseReasons) == 0 {
		t.Fatal("expected a close reason")
	}
	if !strings.Contains(backend.CloseReasons[0], "https://github.com/owner/repo/pull/55") {
		t.Errorf("close reason should contain PR URL, got %q", backend.CloseReasons[0])
	}
}

// CloseTask failure after merge skips the task so the loop doesn't retry it.
func TestFinalizePR_CloseTaskFailure_SkipsTask(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		CloseErr:       fmt.Errorf("exit status 1"),
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix auth bug",
		prNumber:  42,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			return true, nil
		},
	})

	if !result.merged {
		t.Error("PR should still report merged")
	}
	if !result.closed {
		t.Error("closed should be true even on CloseTask failure (task was skipped)")
	}

	// The task must be skipped so the loop doesn't retry it.
	backend.SkipMu.Lock()
	defer backend.SkipMu.Unlock()
	found := false
	for _, id := range backend.SkippedIDs {
		if id == "ralph-abc" {
			found = true
		}
	}
	if !found {
		t.Errorf("task should be skipped after CloseTask failure, skipped=%v", backend.SkippedIDs)
	}

	// Verify the skip reason mentions close failure.
	for i, id := range backend.SkippedIDs {
		if id == "ralph-abc" {
			if !strings.Contains(backend.SkipReasons[i], "close_failed") {
				t.Errorf("skip reason should contain 'close_failed', got %q", backend.SkipReasons[i])
			}
		}
	}
}

// Dependency-blocked CloseTask failure includes blocker IDs in skip reason.
func TestFinalizePR_DependencyBlockedClose_SkipsWithBlockerIDs(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		CloseErr:       fmt.Errorf("exit status 1: cannot close ralph-abc: blocked by open issues [ralph-dep1] (use --force to override)"),
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix auth bug",
		prNumber:  42,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			return true, nil
		},
	})

	backend.SkipMu.Lock()
	defer backend.SkipMu.Unlock()
	found := false
	for i, id := range backend.SkippedIDs {
		if id == "ralph-abc" {
			found = true
			if !strings.Contains(backend.SkipReasons[i], "dependency_blocked_by:ralph-dep1") {
				t.Errorf("skip reason should contain blocker ID, got %q", backend.SkipReasons[i])
			}
		}
	}
	if !found {
		t.Errorf("task should be skipped, skipped=%v", backend.SkippedIDs)
	}
}

// skipTask sets status to open in backend and persists to state.json.
func TestSkipTask_SetsOpenAndPersistsToState(t *testing.T) {
	_, st := setupTestDir(t)
	backend := &testutil.StubBackend{}

	skipTask(backend, st, logging.New(nil), "ralph-xyz", "merge_failed")

	if backend.SkippedTask != "ralph-xyz" {
		t.Errorf("expected backend.SkippedTask=ralph-xyz, got %q", backend.SkippedTask)
	}
	if backend.SkipReason != "merge_failed" {
		t.Errorf("expected backend.SkipReason=merge_failed, got %q", backend.SkipReason)
	}
	skipped, err := st.GetSkippedTasks()
	if err != nil {
		t.Fatal(err)
	}
	if len(skipped) != 1 || skipped[0] != "ralph-xyz" {
		t.Errorf("expected [ralph-xyz] in state.json skipped_tasks, got %v", skipped)
	}
}

// skipTask is a no-op with empty ID.
func TestSkipTask_EmptyID(t *testing.T) {
	_, st := setupTestDir(t)
	backend := &testutil.StubBackend{}

	skipTask(backend, st, logging.New(nil), "", "reason")

	if backend.SkippedTask != "" {
		t.Error("expected no skip with empty ID")
	}
}

// persistCompletedTask takes state and logger — no Loop needed.
func TestPersistCompletedTask_Standalone(t *testing.T) {
	_, st := setupTestDir(t)

	persistCompletedTask(st, logging.New(nil), "ralph-abc", true)

	tasks, err := st.GetCompletedTasks()
	if err != nil {
		t.Fatalf("GetCompletedTasks: %v", err)
	}
	if len(tasks) != 1 {
		t.Fatalf("expected 1 completed task, got %d", len(tasks))
	}
	if tasks[0].ID != "ralph-abc" {
		t.Errorf("expected ID ralph-abc, got %q", tasks[0].ID)
	}
	if !tasks[0].Merged {
		t.Error("merged should be true")
	}
}

// getBeadDescription takes a backend — no Loop or Verifier needed.
func TestGetBeadDescription_Standalone(t *testing.T) {
	backend := &testutil.StubBackend{Description: "Fix auth middleware"}

	desc := getBeadDescription(backend, "ralph-abc")
	if desc != "Fix auth middleware" {
		t.Errorf("expected description, got %q", desc)
	}

	desc = getBeadDescription(backend, "")
	if desc != "" {
		t.Errorf("empty taskID should return empty, got %q", desc)
	}

	desc = getBeadDescription(nil, "ralph-abc")
	if desc != "" {
		t.Errorf("nil backend should return empty, got %q", desc)
	}
}
