package loop

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/brokenalarms/ralph/internal/git"
	"github.com/brokenalarms/ralph/internal/logging"
	"github.com/brokenalarms/ralph/internal/state"
	"github.com/brokenalarms/ralph/internal/testutil"
	"github.com/brokenalarms/ralph/internal/workctx"
)

// buildPRBody assembles description, acceptance criteria, and agent summary
// into a structured PR body when all context is available.
// buildPRBody is a standalone function — takes backend directly, no Loop needed.
func TestBuildPRBody_FullContext(t *testing.T) {
	backend := &testutil.StubBackend{
		Description: "Fix the auth middleware to validate tokens",
		Acceptance:  "1. Tokens are validated\n2. Invalid tokens return 401",
	}

	body := buildPRBody(backend, "ralph-abc", "Fixed auth middleware token validation")

	if !strings.Contains(body, "## Description") {
		t.Error("body should contain Description section")
	}
	if !strings.Contains(body, "Fix the auth middleware") {
		t.Error("body should contain bead description")
	}
	if !strings.Contains(body, "## Acceptance Criteria") {
		t.Error("body should contain Acceptance Criteria section")
	}
	if !strings.Contains(body, "Tokens are validated") {
		t.Error("body should contain acceptance criteria content")
	}
	if !strings.Contains(body, "## Summary") {
		t.Error("body should contain Summary section")
	}
	if !strings.Contains(body, "Fixed auth middleware") {
		t.Error("body should contain agent summary")
	}
}

func TestBuildPRBody_NoBeadDescription(t *testing.T) {
	backend := &testutil.StubBackend{}

	body := buildPRBody(backend, "ralph-abc", "Implemented the feature")

	if strings.Contains(body, "## Description") {
		t.Error("body should not contain Description when bead has none")
	}
	if !strings.Contains(body, "## Summary") {
		t.Error("body should contain Summary section as fallback")
	}
	if !strings.Contains(body, "Implemented the feature") {
		t.Error("body should contain agent summary")
	}
}

func TestBuildPRBody_NoContext(t *testing.T) {
	backend := &testutil.StubBackend{}

	body := buildPRBody(backend, "", "")

	if body != "" {
		t.Errorf("body should be empty when no context is available, got %q", body)
	}
}

func TestBuildPRBody_NeverGeneric(t *testing.T) {
	backend := &testutil.StubBackend{
		Description: "Some task description",
	}

	body := buildPRBody(backend, "ralph-abc", "completed task")

	if strings.Contains(body, "Automated PR for") {
		t.Error("body must not contain generic 'Automated PR for' text")
	}
	if strings.Contains(body, "Generated by ralph") {
		t.Error("body must not contain generic 'Generated by ralph' text")
	}
}

// getPRBase takes only a GitHub interface and workDir — no Loop needed.
func TestGetPRBase_Standalone(t *testing.T) {
	gh := &git.StubGitHub{IsAvailable: true, PRBase: "main"}
	base := getPRBase(gh, "/tmp", "42")
	if base != "main" {
		t.Errorf("expected 'main', got %q", base)
	}

	base = getPRBase(nil, "/tmp", "42")
	if base != "" {
		t.Errorf("nil gh should return empty, got %q", base)
	}

	gh = &git.StubGitHub{IsAvailable: false}
	base = getPRBase(gh, "/tmp", "42")
	if base != "" {
		t.Errorf("unavailable gh should return empty, got %q", base)
	}
}

// finalizePR skips merge and closes the bead when AutoMerge is off.
func TestFinalizePR_NoAutoMerge_ClosesTask(t *testing.T) {
	project, _ := initBareRepoWithOrigin(t)
	ralphDir := filepath.Join(project, ".ralph")
	os.MkdirAll(ralphDir, 0o755)
	st := state.NewStore(ralphDir)
	st.Init(5)
	promptsDir := filepath.Join(project, "prompts")
	createPromptTemplates(t, promptsDir)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &git.Manager{ProjectDir: project, WorkDir: project, Logger: logging.New(nil), BaseBranch: "main"}
	l := New(Config{
		Dirs:         workctx.WorkContext{ProjectDir: project, WorkDir: project, RalphDir: ralphDir, PromptsDir: promptsDir},
		CallsPerHour: 80,
		TaskBackend:  backend,
		AutoMerge:    false,
	}, st, gm, logging.New(nil))
	l.runner = &stubRunner{}

	result := l.finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-abc",
		nextTask: "Fix auth bug",
		prNumber: "42",
		prState:  "OPEN",
		workDir:  project,
	})

	if result.merged {
		t.Error("should not merge when AutoMerge is disabled")
	}
	if !result.closed {
		t.Error("task should be closed even without merge")
	}
	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-abc" {
		t.Errorf("expected CloseTask for ralph-abc, got %v", backend.ClosedIDs)
	}
}

// finalizePR merges and closes when AutoMerge is on and merge succeeds.
func TestFinalizePR_AutoMerge_MergesAndCloses(t *testing.T) {
	project, _ := initBareRepoWithOrigin(t)
	ralphDir := filepath.Join(project, ".ralph")
	os.MkdirAll(ralphDir, 0o755)
	st := state.NewStore(ralphDir)
	st.Init(5)
	promptsDir := filepath.Join(project, "prompts")
	createPromptTemplates(t, promptsDir)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	mergeCalled := false
	gm := &git.Manager{ProjectDir: project, WorkDir: project, Logger: logging.New(nil), BaseBranch: "main"}
	l := New(Config{
		Dirs:         workctx.WorkContext{ProjectDir: project, WorkDir: project, RalphDir: ralphDir, PromptsDir: promptsDir},
		CallsPerHour: 80,
		TaskBackend:  backend,
		AutoMerge:    true,
	}, st, gm, logging.New(nil))
	l.runner = &stubRunner{}
	l.mergeFunc = func(ctx context.Context) (bool, error) {
		mergeCalled = true
		return true, nil
	}

	result := l.finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-xyz",
		nextTask: "Add feature",
		prNumber: "42",
		prState:  "OPEN",
		workDir:  project,
	})

	if !mergeCalled {
		t.Error("merge should have been called")
	}
	if !result.merged {
		t.Error("should be merged when merge returns true")
	}
	if !result.closed {
		t.Error("task should be closed after merge")
	}
	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-xyz" {
		t.Errorf("expected CloseTask for ralph-xyz, got %v", backend.ClosedIDs)
	}
}

// finalizePR skips the task when merge fails with AutoMerge on.
func TestFinalizePR_MergeFailure_SkipsTask(t *testing.T) {
	project, _ := initBareRepoWithOrigin(t)
	ralphDir := filepath.Join(project, ".ralph")
	os.MkdirAll(ralphDir, 0o755)
	st := state.NewStore(ralphDir)
	st.Init(5)
	promptsDir := filepath.Join(project, "prompts")
	createPromptTemplates(t, promptsDir)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &git.Manager{ProjectDir: project, WorkDir: project, Logger: logging.New(nil), BaseBranch: "main"}
	l := New(Config{
		Dirs:         workctx.WorkContext{ProjectDir: project, WorkDir: project, RalphDir: ralphDir, PromptsDir: promptsDir},
		CallsPerHour: 80,
		TaskBackend:  backend,
		AutoMerge:    true,
	}, st, gm, logging.New(nil))
	l.runner = &stubRunner{}
	l.mergeFunc = func(ctx context.Context) (bool, error) {
		return false, fmt.Errorf("merge conflict")
	}

	result := l.finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-abc",
		nextTask: "Fix bug",
		prNumber: "99",
		prState:  "OPEN",
		workDir:  project,
	})

	if result.merged {
		t.Error("should not be merged on failure")
	}
	if result.closed {
		t.Error("task should not be closed on merge failure")
	}
	backend.SkipMu.Lock()
	defer backend.SkipMu.Unlock()
	found := false
	for _, id := range backend.SkippedIDs {
		if id == "ralph-abc" {
			found = true
		}
	}
	if !found {
		t.Error("expected ralph-abc deferred in backend after merge failure")
	}
}

// finalizePR with MERGED state closes immediately without attempting merge.
func TestFinalizePR_AlreadyMerged_ClosesImmediately(t *testing.T) {
	project, _ := initBareRepoWithOrigin(t)
	ralphDir := filepath.Join(project, ".ralph")
	os.MkdirAll(ralphDir, 0o755)
	st := state.NewStore(ralphDir)
	st.Init(5)
	promptsDir := filepath.Join(project, "prompts")
	createPromptTemplates(t, promptsDir)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &git.Manager{ProjectDir: project, WorkDir: project, Logger: logging.New(nil), BaseBranch: "main"}
	l := New(Config{
		Dirs:         workctx.WorkContext{ProjectDir: project, WorkDir: project, RalphDir: ralphDir, PromptsDir: promptsDir},
		CallsPerHour: 80,
		TaskBackend:  backend,
		AutoMerge:    true,
	}, st, gm, logging.New(nil))
	l.runner = &stubRunner{}
	l.mergeFunc = func(ctx context.Context) (bool, error) {
		t.Fatal("merge should not be called for already-merged PR")
		return false, nil
	}

	result := l.finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-xyz",
		nextTask: "Add feature",
		prNumber: "42",
		prState:  "MERGED",
		workDir:  project,
	})

	if !result.merged {
		t.Error("should report merged for MERGED state")
	}
	if !result.closed {
		t.Error("task should be closed")
	}
	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-xyz" {
		t.Errorf("expected CloseTask for ralph-xyz, got %v", backend.ClosedIDs)
	}
}

// finalizePR uses PR URL in close reason when available.
func TestFinalizePR_UsesURLInCloseReason(t *testing.T) {
	project, _ := initBareRepoWithOrigin(t)
	ralphDir := filepath.Join(project, ".ralph")
	os.MkdirAll(ralphDir, 0o755)
	st := state.NewStore(ralphDir)
	st.Init(5)
	promptsDir := filepath.Join(project, "prompts")
	createPromptTemplates(t, promptsDir)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &git.Manager{ProjectDir: project, WorkDir: project, Logger: logging.New(nil), BaseBranch: "main"}
	l := New(Config{
		Dirs:         workctx.WorkContext{ProjectDir: project, WorkDir: project, RalphDir: ralphDir, PromptsDir: promptsDir},
		CallsPerHour: 80,
		TaskBackend:  backend,
	}, st, gm, logging.New(nil))
	l.runner = &stubRunner{}

	l.finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-abc",
		nextTask: "Fix login",
		prNumber: "55",
		prState:  "OPEN",
		prURL:    "https://github.com/owner/repo/pull/55",
		workDir:  project,
	})

	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.CloseReasons) == 0 {
		t.Fatal("expected a close reason")
	}
	if !strings.Contains(backend.CloseReasons[0], "https://github.com/owner/repo/pull/55") {
		t.Errorf("close reason should contain PR URL, got %q", backend.CloseReasons[0])
	}
}

// skipTask sets status to open in backend and persists to state.json.
func TestSkipTask_SetsOpenAndPersistsToState(t *testing.T) {
	_, st := setupTestDir(t)
	backend := &testutil.StubBackend{}

	skipTask(backend, st, logging.New(nil), "ralph-xyz", "merge_failed")

	if backend.SkippedTask != "ralph-xyz" {
		t.Errorf("expected backend.SkippedTask=ralph-xyz, got %q", backend.SkippedTask)
	}
	if backend.SkipReason != "merge_failed" {
		t.Errorf("expected backend.SkipReason=merge_failed, got %q", backend.SkipReason)
	}
	skipped, err := st.GetSkippedTasks()
	if err != nil {
		t.Fatal(err)
	}
	if len(skipped) != 1 || skipped[0] != "ralph-xyz" {
		t.Errorf("expected [ralph-xyz] in state.json skipped_tasks, got %v", skipped)
	}
}

// skipTask is a no-op with empty ID.
func TestSkipTask_EmptyID(t *testing.T) {
	_, st := setupTestDir(t)
	backend := &testutil.StubBackend{}

	skipTask(backend, st, logging.New(nil), "", "reason")

	if backend.SkippedTask != "" {
		t.Error("expected no skip with empty ID")
	}
}

// persistCompletedTask takes state and logger — no Loop needed.
func TestPersistCompletedTask_Standalone(t *testing.T) {
	_, st := setupTestDir(t)

	persistCompletedTask(st, logging.New(nil), "ralph-abc")

	tasks, err := st.GetCompletedTasks()
	if err != nil {
		t.Fatalf("GetCompletedTasks: %v", err)
	}
	if len(tasks) != 1 {
		t.Fatalf("expected 1 completed task, got %d", len(tasks))
	}
	if tasks[0] != "ralph-abc" {
		t.Errorf("expected ID ralph-abc, got %q", tasks[0])
	}
}

// getBeadDescription takes a backend — no Loop or Verifier needed.
func TestGetBeadDescription_Standalone(t *testing.T) {
	backend := &testutil.StubBackend{Description: "Fix auth middleware"}

	desc := getBeadDescription(backend, "ralph-abc")
	if desc != "Fix auth middleware" {
		t.Errorf("expected description, got %q", desc)
	}

	desc = getBeadDescription(backend, "")
	if desc != "" {
		t.Errorf("empty taskID should return empty, got %q", desc)
	}

	desc = getBeadDescription(nil, "ralph-abc")
	if desc != "" {
		t.Errorf("nil backend should return empty, got %q", desc)
	}
}
