package loop

import (
	"context"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/brokenalarms/ralph/internal/attempts"
	"github.com/brokenalarms/ralph/internal/git"
	"github.com/brokenalarms/ralph/internal/logging"
	"github.com/brokenalarms/ralph/internal/testutil"
)

// buildPRBody assembles description, acceptance criteria, and agent summary
// into a structured PR body when all context is available.
// buildPRBody is a standalone function — takes backend directly, no Loop needed.
func TestBuildPRBody_FullContext(t *testing.T) {
	backend := &testutil.StubBackend{
		Description: "Fix the auth middleware to validate tokens",
		Acceptance:  "1. Tokens are validated\n2. Invalid tokens return 401",
	}

	body := buildPRBody(backend, "ralph-abc", "Fixed auth middleware token validation")

	if !strings.Contains(body, "## Description") {
		t.Error("body should contain Description section")
	}
	if !strings.Contains(body, "Fix the auth middleware") {
		t.Error("body should contain bead description")
	}
	if !strings.Contains(body, "## Acceptance Criteria") {
		t.Error("body should contain Acceptance Criteria section")
	}
	if !strings.Contains(body, "Tokens are validated") {
		t.Error("body should contain acceptance criteria content")
	}
	if !strings.Contains(body, "## Summary") {
		t.Error("body should contain Summary section")
	}
	if !strings.Contains(body, "Fixed auth middleware") {
		t.Error("body should contain agent summary")
	}
}

func TestBuildPRBody_NoBeadDescription(t *testing.T) {
	backend := &testutil.StubBackend{}

	body := buildPRBody(backend, "ralph-abc", "Implemented the feature")

	if strings.Contains(body, "## Description") {
		t.Error("body should not contain Description when bead has none")
	}
	if !strings.Contains(body, "## Summary") {
		t.Error("body should contain Summary section as fallback")
	}
	if !strings.Contains(body, "Implemented the feature") {
		t.Error("body should contain agent summary")
	}
}

func TestBuildPRBody_NoContext(t *testing.T) {
	backend := &testutil.StubBackend{}

	body := buildPRBody(backend, "", "")

	if body != "" {
		t.Errorf("body should be empty when no context is available, got %q", body)
	}
}

func TestBuildPRBody_NeverGeneric(t *testing.T) {
	backend := &testutil.StubBackend{
		Description: "Some task description",
	}

	body := buildPRBody(backend, "ralph-abc", "completed task")

	if strings.Contains(body, "Automated PR for") {
		t.Error("body must not contain generic 'Automated PR for' text")
	}
	if strings.Contains(body, "Generated by ralph") {
		t.Error("body must not contain generic 'Generated by ralph' text")
	}
}

// finalizePR skips merge and closes the bead when AutoMerge is off.
func TestFinalizePR_NoAutoMerge_ClosesTask(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix auth bug",
		prNumber:  42,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: false,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
	})

	if result.merged {
		t.Error("should not merge when AutoMerge is disabled")
	}
	if !result.closed {
		t.Error("task should be closed even without merge")
	}
	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-abc" {
		t.Errorf("expected CloseTask for ralph-abc, got %v", backend.ClosedIDs)
	}
}

// finalizePR merges and closes when AutoMerge is on and merge succeeds.
func TestFinalizePR_AutoMerge_MergesAndCloses(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	mergeCalled := false
	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-xyz",
		nextTask:  "Add feature",
		prNumber:  42,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			mergeCalled = true
			return true, nil
		},
	})

	if !mergeCalled {
		t.Error("merge should have been called")
	}
	if !result.merged {
		t.Error("should be merged when merge returns true")
	}
	if !result.closed {
		t.Error("task should be closed after merge")
	}
	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-xyz" {
		t.Errorf("expected CloseTask for ralph-xyz, got %v", backend.ClosedIDs)
	}
}

// finalizePR closes the bead (not skips) when merge fails with AutoMerge on.
// Work is verified — it should land in completed_tasks so setStackHead can find
// the branch for the next task to stack on.
func TestFinalizePR_MergeFailure_ClosesTask(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix bug",
		prNumber:  99,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			return false, fmt.Errorf("merge conflict")
		},
	})

	if result.merged {
		t.Error("should not be merged on failure")
	}
	if !result.closed {
		t.Error("task should be closed (not skipped) after merge failure — work is verified")
	}

	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-abc" {
		t.Errorf("expected CloseTask for ralph-abc, got %v", backend.ClosedIDs)
	}
	if len(backend.CloseReasons) == 0 || !strings.Contains(backend.CloseReasons[0], "merge pending") {
		t.Errorf("close reason should indicate merge pending, got %v", backend.CloseReasons)
	}
}

// When CI fix agents apply code changes but CI is still failing after all merge
// attempts, finalizePR leaves the task open for manual investigation. The task
// is NOT closed as "verified" — phase stays at implementing.
func TestFinalizePR_CIFixExhausted_TaskStaysOpen(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix failing tests",
		prNumber:  99,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			return false, &git.CIFixExhaustedError{Attempts: 3}
		},
	})

	if result.closed {
		t.Error("task should NOT be closed when CI fix agents exhausted — tests still failing")
	}
	if result.merged {
		t.Error("task should not be merged")
	}
	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 0 {
		t.Errorf("CloseTask must not be called when CI fix agents exhausted, got %v", backend.ClosedIDs)
	}
}

// finalizePR with merge failure records merged:false in completed_tasks so
// setStackHead can find the unmerged branch for the next task to stack on.
func TestFinalizePR_MergeFailure_AppearsInCompletedTasksWithMergedFalse(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix bug",
		prNumber:  99,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			return false, fmt.Errorf("CI check failed")
		},
	})

	tasks, err := st.GetCompletedTasks()
	if err != nil {
		t.Fatalf("GetCompletedTasks: %v", err)
	}
	if len(tasks) != 1 {
		t.Fatalf("expected 1 entry in completed_tasks, got %d", len(tasks))
	}
	if tasks[0].ID != "ralph-abc" {
		t.Errorf("completed task ID = %q, want ralph-abc", tasks[0].ID)
	}
	if tasks[0].Merged {
		t.Error("merged should be false for unmerged PR")
	}
}

// finalizePR with MERGED state closes immediately without attempting merge.
func TestFinalizePR_AlreadyMerged_ClosesImmediately(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-xyz",
		nextTask:  "Add feature",
		prNumber:  42,
		prState:   "MERGED",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			t.Fatal("merge should not be called for already-merged PR")
			return false, nil
		},
	})

	if !result.merged {
		t.Error("should report merged for MERGED state")
	}
	if !result.closed {
		t.Error("task should be closed")
	}
	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.ClosedIDs) != 1 || backend.ClosedIDs[0] != "ralph-xyz" {
		t.Errorf("expected CloseTask for ralph-xyz, got %v", backend.ClosedIDs)
	}
}

// finalizePR uses PR URL in close reason when available.
func TestFinalizePR_UsesURLInCloseReason(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix login",
		prNumber:  55,
		prState:   "OPEN",
		prURL:     "https://github.com/owner/repo/pull/55",
		workDir:   dir,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
	})

	backend.CloseMu.Lock()
	defer backend.CloseMu.Unlock()
	if len(backend.CloseReasons) == 0 {
		t.Fatal("expected a close reason")
	}
	if !strings.Contains(backend.CloseReasons[0], "https://github.com/owner/repo/pull/55") {
		t.Errorf("close reason should contain PR URL, got %q", backend.CloseReasons[0])
	}
}

// CloseTask failure after merge skips the task so the loop doesn't retry it.
func TestFinalizePR_CloseTaskFailure_SkipsTask(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		CloseErr:       fmt.Errorf("exit status 1"),
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	result := finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix auth bug",
		prNumber:  42,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			return true, nil
		},
	})

	if !result.merged {
		t.Error("PR should still report merged")
	}
	if !result.closed {
		t.Error("closed should be true even on CloseTask failure (task was skipped)")
	}

	// The task must be skipped so the loop doesn't retry it.
	backend.SkipMu.Lock()
	defer backend.SkipMu.Unlock()
	found := false
	for _, id := range backend.SkippedIDs {
		if id == "ralph-abc" {
			found = true
		}
	}
	if !found {
		t.Errorf("task should be skipped after CloseTask failure, skipped=%v", backend.SkippedIDs)
	}

	// Verify the skip reason mentions close failure.
	for i, id := range backend.SkippedIDs {
		if id == "ralph-abc" {
			if !strings.Contains(backend.SkipReasons[i], "close_failed") {
				t.Errorf("skip reason should contain 'close_failed', got %q", backend.SkipReasons[i])
			}
		}
	}
}

// Dependency-blocked CloseTask failure includes blocker IDs in skip reason.
func TestFinalizePR_DependencyBlockedClose_SkipsWithBlockerIDs(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		CloseErr:       fmt.Errorf("exit status 1: cannot close ralph-abc: blocked by open issues [ralph-dep1] (use --force to override)"),
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:       context.Background(),
		taskID:    "ralph-abc",
		nextTask:  "Fix auth bug",
		prNumber:  42,
		prState:   "OPEN",
		workDir:   dir,
		autoMerge: true,
		git:       gm,
		logger:    logging.New(nil),
		backend:   backend,
		state:     st,
		attempts:  attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) {
			return true, nil
		},
	})

	backend.SkipMu.Lock()
	defer backend.SkipMu.Unlock()
	found := false
	for i, id := range backend.SkippedIDs {
		if id == "ralph-abc" {
			found = true
			if !strings.Contains(backend.SkipReasons[i], "dependency_blocked_by:ralph-dep1") {
				t.Errorf("skip reason should contain blocker ID, got %q", backend.SkipReasons[i])
			}
		}
	}
	if !found {
		t.Errorf("task should be skipped, skipped=%v", backend.SkippedIDs)
	}
}

// finalizePR calls PollReview for each active reviewer when the PR is OPEN with autoMerge on.
func TestFinalizePR_ActiveReviewer_PollsCalled(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-abc",
		nextTask: "Fix bug",
		prNumber: 42,
		prState:  "OPEN",
		workDir:  dir,
		autoMerge: true,
		activeReviewers: []git.Reviewer{
			{AppSlug: "copilot-code-review", BotUsername: "copilot-pull-request-reviewer", DefaultTimeout: 120 * time.Second},
		},
		git:      gm,
		logger:   logging.New(nil),
		backend:  backend,
		state:    st,
		attempts: attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) { return true, nil },
	})

	if !gm.PollReviewCalled {
		t.Error("PollReview should be called when activeReviewers is set and PR is OPEN")
	}
}

// finalizePR uses the per-reviewer DefaultTimeout from the registry — 30s when
// review_on_push=false (opportunistic), as set by DetectActiveReviewers.
func TestFinalizePR_ActiveReviewer_ShortTimeoutWhenReviewOnPushFalse(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-abc",
		nextTask: "Fix bug",
		prNumber: 42,
		prState:  "OPEN",
		workDir:  dir,
		autoMerge: true,
		activeReviewers: []git.Reviewer{
			{AppSlug: "copilot-code-review", BotUsername: "copilot-pull-request-reviewer", DefaultTimeout: 30 * time.Second, ReviewOnPush: false},
		},
		git:      gm,
		logger:   logging.New(nil),
		backend:  backend,
		state:    st,
		attempts: attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) { return true, nil },
	})

	if !gm.PollReviewCalled {
		t.Error("PollReview should be called even with review_on_push=false")
	}
	if gm.PollReviewLastTimeout != 30*time.Second {
		t.Errorf("expected 30s poll timeout when reviewer has 30s DefaultTimeout, got %v", gm.PollReviewLastTimeout)
	}
}

// finalizePR uses 120s timeout when the reviewer has DefaultTimeout=120s (review_on_push=true).
func TestFinalizePR_ActiveReviewer_FullTimeoutWhenReviewOnPushTrue(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-abc",
		nextTask: "Fix bug",
		prNumber: 42,
		prState:  "OPEN",
		workDir:  dir,
		autoMerge: true,
		activeReviewers: []git.Reviewer{
			{AppSlug: "copilot-code-review", BotUsername: "copilot-pull-request-reviewer", DefaultTimeout: 120 * time.Second, ReviewOnPush: true},
		},
		git:      gm,
		logger:   logging.New(nil),
		backend:  backend,
		state:    st,
		attempts: attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) { return true, nil },
	})

	if !gm.PollReviewCalled {
		t.Error("PollReview should be called with review_on_push=true")
	}
	if gm.PollReviewLastTimeout != 120*time.Second {
		t.Errorf("expected 120s poll timeout when reviewer has 120s DefaultTimeout, got %v", gm.PollReviewLastTimeout)
	}
}

// finalizePR does not call PollReview when activeReviewers is empty.
func TestFinalizePR_NoActiveReviewers_NoPoll(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:             context.Background(),
		taskID:          "ralph-abc",
		nextTask:        "Fix bug",
		prNumber:        42,
		prState:         "OPEN",
		workDir:         dir,
		autoMerge:       true,
		activeReviewers: nil,
		git:             gm,
		logger:          logging.New(nil),
		backend:         backend,
		state:           st,
		attempts:        attempts.New(dir),
		mergeFunc:       func(ctx context.Context) (bool, error) { return true, nil },
	})

	if gm.PollReviewCalled {
		t.Error("PollReview should not be called when activeReviewers is empty")
	}
}

// skipTask sets status to open in backend and persists to state.json.
func TestSkipTask_SetsOpenAndPersistsToState(t *testing.T) {
	_, st := setupTestDir(t)
	backend := &testutil.StubBackend{}

	skipTask(backend, st, logging.New(nil), "ralph-xyz", "merge_failed")

	if backend.SkippedTask != "ralph-xyz" {
		t.Errorf("expected backend.SkippedTask=ralph-xyz, got %q", backend.SkippedTask)
	}
	if backend.SkipReason != "merge_failed" {
		t.Errorf("expected backend.SkipReason=merge_failed, got %q", backend.SkipReason)
	}
	skipped, err := st.GetSkippedTasks()
	if err != nil {
		t.Fatal(err)
	}
	if len(skipped) != 1 || skipped[0] != "ralph-xyz" {
		t.Errorf("expected [ralph-xyz] in state.json skipped_tasks, got %v", skipped)
	}
}

// skipTask is a no-op with empty ID.
func TestSkipTask_EmptyID(t *testing.T) {
	_, st := setupTestDir(t)
	backend := &testutil.StubBackend{}

	skipTask(backend, st, logging.New(nil), "", "reason")

	if backend.SkippedTask != "" {
		t.Error("expected no skip with empty ID")
	}
}

// persistCompletedTask takes state and logger — no Loop needed.
func TestPersistCompletedTask_Standalone(t *testing.T) {
	_, st := setupTestDir(t)

	persistCompletedTask(st, logging.New(nil), "ralph-abc", true)

	tasks, err := st.GetCompletedTasks()
	if err != nil {
		t.Fatalf("GetCompletedTasks: %v", err)
	}
	if len(tasks) != 1 {
		t.Fatalf("expected 1 completed task, got %d", len(tasks))
	}
	if tasks[0].ID != "ralph-abc" {
		t.Errorf("expected ID ralph-abc, got %q", tasks[0].ID)
	}
	if !tasks[0].Merged {
		t.Error("merged should be true")
	}
}

// finalizePR spawns a fix agent when a reviewer returns actionable comments.
func TestFinalizePR_AutoReview_ActionableComments_SpawnsFixAgent(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	fixAgentSpawned := false
	v := newTestVerifier(t, func(v *Verifier) {
		v.deps.NewRunner = func() claudeRunner {
			fixAgentSpawned = true
			return &stubRunner{result: stubResult(true, "addressed nil check")}
		}
	})

	gm := &testutil.StubGit{
		ProjectDir: dir,
		WorkDir:    dir,
		PollReviewResult: &git.AutoReview{
			Body: "Review",
			Comments: []git.ReviewComment{
				{Path: "pkg/foo.go", Line: 42, Body: "Missing nil check — this will panic"},
			},
		},
	}

	finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-abc",
		nextTask: "Fix bug",
		prNumber: 42,
		prState:  "OPEN",
		workDir:  dir,
		autoMerge: true,
		activeReviewers: []git.Reviewer{
			{AppSlug: "copilot-code-review", BotUsername: "copilot-pull-request-reviewer", DefaultTimeout: 120 * time.Second},
		},
		git:      gm,
		logger:   logging.New(nil),
		backend:  backend,
		state:    st,
		attempts: attempts.New(dir),
		verifier: v,
		mergeFunc: func(ctx context.Context) (bool, error) { return true, nil },
	})

	if !fixAgentSpawned {
		t.Error("fix agent should be spawned when reviewer has actionable comments")
	}
}

// finalizePR does not spawn a fix agent when review has no actionable comments.
func TestFinalizePR_AutoReview_InformationalOnly_NoFixAgent(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	fixAgentSpawned := false
	v := newTestVerifier(t, func(v *Verifier) {
		v.deps.NewRunner = func() claudeRunner {
			fixAgentSpawned = true
			return &stubRunner{result: stubResult(true, "done")}
		}
	})

	gm := &testutil.StubGit{
		ProjectDir: dir,
		WorkDir:    dir,
		PollReviewResult: &git.AutoReview{
			Body: "LGTM",
			Comments: []git.ReviewComment{
				{Path: "pkg/foo.go", Line: 1, Body: "This PR adds caching support."},
			},
		},
	}

	finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-abc",
		nextTask: "Fix bug",
		prNumber: 42,
		prState:  "OPEN",
		workDir:  dir,
		autoMerge: true,
		activeReviewers: []git.Reviewer{
			{AppSlug: "copilot-code-review", BotUsername: "copilot-pull-request-reviewer", DefaultTimeout: 120 * time.Second},
		},
		git:      gm,
		logger:   logging.New(nil),
		backend:  backend,
		state:    st,
		attempts: attempts.New(dir),
		verifier: v,
		mergeFunc: func(ctx context.Context) (bool, error) { return true, nil },
	})

	if fixAgentSpawned {
		t.Error("fix agent should not be spawned for purely informational review comments")
	}
}

// finalizePR does not re-poll when a reviewer's feedback was already addressed in state.
func TestFinalizePR_AutoReview_AlreadyAddressed_NoPoll(t *testing.T) {
	dir, st := setupTestDir(t)

	// Pre-seed the addressed flag in state using the per-reviewer key.
	st.Write("review_addressed:copilot-pull-request-reviewer:ralph-abc", "true")

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	gm := &testutil.StubGit{ProjectDir: dir, WorkDir: dir}

	finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-abc",
		nextTask: "Fix bug",
		prNumber: 42,
		prState:  "OPEN",
		workDir:  dir,
		autoMerge: true,
		activeReviewers: []git.Reviewer{
			{AppSlug: "copilot-code-review", BotUsername: "copilot-pull-request-reviewer", DefaultTimeout: 120 * time.Second},
		},
		git:      gm,
		logger:   logging.New(nil),
		backend:  backend,
		state:    st,
		attempts: attempts.New(dir),
		mergeFunc: func(ctx context.Context) (bool, error) { return true, nil },
	})

	if gm.PollReviewCalled {
		t.Error("PollReview should not be called when reviewer feedback was already addressed")
	}
}

// finalizePR marks review as addressed per-reviewer in state after processing,
// preventing re-poll on subsequent calls for the same task.
func TestFinalizePR_AutoReview_SetsAddressedFlag(t *testing.T) {
	dir, st := setupTestDir(t)

	backend := &testutil.TrackingBackend{
		MutableBackend: testutil.MutableBackend{StubBackend: testutil.StubBackend{Remaining: 1, Total: 1}},
	}

	v := newTestVerifier(t, func(v *Verifier) {
		v.deps.NewRunner = func() claudeRunner {
			return &stubRunner{result: stubResult(true, "done")}
		}
	})

	gm := &testutil.StubGit{
		ProjectDir: dir,
		WorkDir:    dir,
		PollReviewResult: &git.AutoReview{
			Comments: []git.ReviewComment{
				{Path: "pkg/foo.go", Line: 5, Body: "Missing nil check"},
			},
		},
	}

	finalizePR(finalizePRParams{
		ctx:      context.Background(),
		taskID:   "ralph-abc",
		nextTask: "Fix bug",
		prNumber: 42,
		prState:  "OPEN",
		workDir:  dir,
		autoMerge: true,
		activeReviewers: []git.Reviewer{
			{AppSlug: "copilot-code-review", BotUsername: "copilot-pull-request-reviewer", DefaultTimeout: 120 * time.Second},
		},
		git:      gm,
		logger:   logging.New(nil),
		backend:  backend,
		state:    st,
		attempts: attempts.New(dir),
		verifier: v,
		mergeFunc: func(ctx context.Context) (bool, error) { return true, nil },
	})

	addressed, _ := st.Read("review_addressed:copilot-pull-request-reviewer:ralph-abc")
	if addressed != "true" {
		t.Errorf("state should have review_addressed:copilot-pull-request-reviewer:ralph-abc=true after review processed, got %q", addressed)
	}
}

// isActionableComment classifies comments correctly.
func TestIsActionableComment(t *testing.T) {
	tests := []struct {
		name       string
		comment    git.ReviewComment
		actionable bool
	}{
		{
			name:       "suggestion block",
			comment:    git.ReviewComment{Path: "foo.go", Line: 1, Body: "```suggestion\nfixed code\n```"},
			actionable: true,
		},
		{
			name:       "nil check keyword",
			comment:    git.ReviewComment{Path: "foo.go", Line: 5, Body: "Missing nil check before using ptr"},
			actionable: true,
		},
		{
			name:       "bug keyword",
			comment:    git.ReviewComment{Path: "bar.go", Line: 10, Body: "This is a bug — value may overflow"},
			actionable: true,
		},
		{
			name:       "code block on file comment",
			comment:    git.ReviewComment{Path: "bar.go", Line: 3, Body: "Consider:\n```go\nreturn err\n```"},
			actionable: true,
		},
		{
			name:       "informational summary",
			comment:    git.ReviewComment{Path: "bar.go", Line: 1, Body: "This PR adds caching support to the auth layer."},
			actionable: false,
		},
		{
			name:       "empty body",
			comment:    git.ReviewComment{Path: "foo.go", Line: 1, Body: ""},
			actionable: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := isActionableComment(tc.comment)
			if got != tc.actionable {
				t.Errorf("isActionableComment(%q) = %v, want %v", tc.comment.Body, got, tc.actionable)
			}
		})
	}
}

// formatReviewContext structures comments with file paths, line numbers, and reviewer name.
func TestFormatReviewContext(t *testing.T) {
	comments := []git.ReviewComment{
		{Path: "pkg/auth.go", Line: 42, Body: "Missing nil check"},
		{Path: "pkg/db.go", Line: 17, Body: "```suggestion\nreturn nil, err\n```"},
	}

	result := formatReviewContext("copilot-pull-request-reviewer", 99, comments)

	if !strings.Contains(result, "PR #99") {
		t.Error("context should mention PR number")
	}
	if !strings.Contains(result, "copilot-pull-request-reviewer") {
		t.Error("context should mention reviewer name")
	}
	if !strings.Contains(result, "pkg/auth.go:42") {
		t.Error("context should contain file:line for first comment")
	}
	if !strings.Contains(result, "Missing nil check") {
		t.Error("context should contain first comment body")
	}
	if !strings.Contains(result, "pkg/db.go:17") {
		t.Error("context should contain file:line for second comment")
	}
}

// getBeadDescription takes a backend — no Loop or Verifier needed.
func TestGetBeadDescription_Standalone(t *testing.T) {
	backend := &testutil.StubBackend{Description: "Fix auth middleware"}

	desc := getBeadDescription(backend, "ralph-abc")
	if desc != "Fix auth middleware" {
		t.Errorf("expected description, got %q", desc)
	}

	desc = getBeadDescription(backend, "")
	if desc != "" {
		t.Errorf("empty taskID should return empty, got %q", desc)
	}

	desc = getBeadDescription(nil, "ralph-abc")
	if desc != "" {
		t.Errorf("nil backend should return empty, got %q", desc)
	}
}
