package git

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/brokenalarms/ralph/internal/logging"
)

// PushAndCreatePR pushes the current branch to remote and creates a PR if
// none exists. This ensures the Go code owns the push/PR lifecycle rather
// than relying on Claude to do it.
func (m *Manager) PushAndCreatePR(ctx context.Context, taskID, taskDesc string) error {
	if m.WorktreeBranch == "" || m.WorkDir == m.ProjectDir {
		return nil
	}

	m.EnsureUpToDate(ctx)

	repoURL := m.gitOutput(m.WorkDir, "remote", "get-url", "origin")
	if repoURL == "" {
		return nil
	}

	// Check if branch has commits beyond the default branch.
	defaultBranch := m.detectDefaultBranch()
	revCount := m.gitOutput(m.WorkDir, "rev-list", "--count", "origin/"+defaultBranch+"..HEAD")
	if revCount == "" || revCount == "0" {
		m.Logger.Log("No new commits to push")
		return nil
	}

	gh := m.gh()
	if !gh.Available() {
		return fmt.Errorf("gh CLI not found — cannot create PR")
	}

	// If the agent already pushed and created a PR, update the title
	// to include the bead ID (the agent may not have included it).
	prNumber, _ := gh.FindOpenPR(m.WorktreeBranch, repoURL)
	if prNumber != "" {
		if taskID != "" {
			title := m.prTitle(taskID, taskDesc)
			if err := gh.EditPR(prNumber, repoURL, title); err != nil {
				m.Logger.Warn("Failed to update PR #%s title: %v", prNumber, err)
			}
		}
		m.Logger.Log("PR #%s exists for %s", prNumber, m.WorktreeBranch)
		return nil
	}

	// Push branch to remote.
	m.Logger.Log("Pushing %s...", m.WorktreeBranch)
	if err := m.gitCmdErrCtx(ctx, m.WorkDir, "push", "-u", "origin", m.WorktreeBranch); err != nil {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		return fmt.Errorf("push failed for %s", m.WorktreeBranch)
	}

	title := m.prTitle(taskID, taskDesc)

	body := fmt.Sprintf("Automated PR for: %s\n\nGenerated by ralph.", taskDesc)
	if err := gh.CreatePR(CreatePROpts{
		Head:  m.WorktreeBranch,
		Base:  defaultBranch,
		Title: title,
		Body:  body,
		Repo:  repoURL,
		Dir:   m.WorkDir,
	}); err != nil {
		return err
	}

	m.Logger.Log("Created PR for %s", m.WorktreeBranch)
	return nil
}

func (m *Manager) prTitle(taskID, taskDesc string) string {
	title := taskDesc
	if taskID != "" {
		title = "[" + taskID + "] " + title
	}
	if len(title) > 70 {
		title = title[:67] + "..."
	}
	if title == "" {
		title = m.WorktreeBranch
	}
	return title
}

// AutoMergeCurrentBranch squash-merges the PR for the current branch into main.
// Returns (true, nil) when a PR was merged, (false, nil) when no PR exists or
// no action was needed, and (false, err) on failure. Returns typed errors
// (CIFailureError, MergeConflictError) that callers can handle.
func (m *Manager) AutoMergeCurrentBranch(ctx context.Context) (bool, error) {
	if m.WorktreeBranch == "" || m.WorkDir == m.ProjectDir {
		return false, nil
	}

	m.EnsureUpToDate(ctx)

	gh := m.gh()
	if !gh.Available() {
		return false, fmt.Errorf("gh CLI not found — cannot auto-merge")
	}

	repoURL := m.gitOutput(m.WorkDir, "remote", "get-url", "origin")
	if repoURL == "" {
		m.Logger.Log("No remote URL — skipping auto-merge")
		return false, nil
	}

	prNumber, err := gh.FindOpenPR(m.WorktreeBranch, repoURL)
	if err != nil || prNumber == "" {
		m.Logger.Log("No open PR found for %s — skipping auto-merge", m.WorktreeBranch)
		return false, nil
	}

	defaultBranch := m.detectDefaultBranch()
	m.Logger.Log("%s Auto-merging PR #%s...", logging.BranchTag(defaultBranch), prNumber)

	fetch := gh.ListChecks

	// Poll CI status before attempting merge.
	checks, fetchErr := fetch(prNumber, repoURL)
	var status CIStatus
	if fetchErr != nil || len(checks) == 0 {
		m.Logger.Log("CI checks not available yet for PR #%s — waiting...", prNumber)
		checks, status, err = waitForCI(ctx, fetch, prNumber, repoURL, DefaultCIPollInterval, DefaultCIPollTimeout, m.Logger)
		if err != nil {
			m.Logger.Warn("CI polling failed for PR #%s: %v — attempting merge anyway", prNumber, err)
		}
	} else {
		status = evaluateChecks(checks)
		if status == CIPending {
			m.Logger.Log("CI checks pending on PR #%s — waiting for completion...", prNumber)
			checks, status, err = waitForCI(ctx, fetch, prNumber, repoURL, DefaultCIPollInterval, DefaultCIPollTimeout, m.Logger)
			if err != nil {
				return false, fmt.Errorf("CI polling failed for PR #%s: %w", prNumber, err)
			}
		}
	}

	if status == CIFailed {
		return false, &CIFailureError{
			PRNumber: prNumber,
			Failures: failedChecks(checks),
		}
	}

	if status == CIPassed {
		m.Logger.Log("CI passed for PR #%s — merging", prNumber)
	}

	// Update the PR branch to include any commits pushed directly to the
	// base branch since our last rebase.
	nwo := nwoFromRemote(repoURL)
	if nwo != "" {
		if updated, updateErr := gh.UpdateBranch(m.WorkDir, nwo, prNumber); updateErr != nil {
			m.Logger.Warn("PR branch update: %v", updateErr)
		} else if updated {
			m.Logger.Log("Updated PR #%s branch with latest base", prNumber)
			checks, status, err = waitForCI(ctx, fetch, prNumber, repoURL, DefaultCIPollInterval, DefaultCIPollTimeout, m.Logger)
			if err != nil {
				m.Logger.Warn("CI polling after branch update: %v — attempting merge anyway", err)
			}
			if status == CIFailed {
				return false, &CIFailureError{
					PRNumber: prNumber,
					Failures: failedChecks(checks),
				}
			}
		}
	}

	opts := m.mergeOpts()
	mergeOutput, mergeErr := gh.MergePR(prNumber, repoURL, opts)
	if mergeErr == nil {
		return m.postMergeUpdate(prNumber)
	}

	if isMergeConflictError(mergeOutput) {
		m.Logger.Warn("PR #%s has merge conflicts — attempting rebase", prNumber)
		return false, &MergeConflictError{PRNumber: prNumber}
	}

	if isCIGatedError(mergeOutput) {
		m.Logger.Log("PR #%s blocked by branch protection — waiting for CI...", prNumber)
		checks, status, waitErr := waitForCI(ctx, fetch, prNumber, repoURL, DefaultCIPollInterval, DefaultCIPollTimeout, m.Logger)
		if waitErr != nil {
			return false, fmt.Errorf("CI polling failed for PR #%s: %w", prNumber, waitErr)
		}
		if status == CIFailed {
			return false, &CIFailureError{
				PRNumber: prNumber,
				Failures: failedChecks(checks),
			}
		}
		if status == CIPassed {
			m.Logger.Log("CI passed for PR #%s — retrying merge", prNumber)
			retryOutput, retryErr := gh.MergePR(prNumber, repoURL, opts)
			if retryErr == nil {
				return m.postMergeUpdate(prNumber)
			}
			m.Logger.Warn("Merge retry failed for PR #%s: %s", prNumber, retryOutput)
			return false, fmt.Errorf("merge retry failed for PR #%s after CI passed", prNumber)
		}
	}

	m.Logger.Warn("Auto-merge failed for PR #%s: %s", prNumber, mergeOutput)
	return false, fmt.Errorf("auto-merge failed for PR #%s", prNumber)
}

// GetCIFailureLog retrieves the failed CI run's log output for the given PR.
func (m *Manager) GetCIFailureLog(prNumber string) string {
	return m.gh().GetRunLog(prNumber, m.WorkDir)
}

// postMergeUpdate fetches the latest default branch after a successful merge
// so the next iteration starts from merged state.
func (m *Manager) postMergeUpdate(prNumber string) (bool, error) {
	defaultBranch := m.detectDefaultBranch()
	m.Logger.Log("%s PR #%s squash-merged", logging.BranchTag(defaultBranch), prNumber)
	m.gitCmd(m.ProjectDir, "fetch", "origin", defaultBranch)
	// Single atomic reset: advances ref, index, and working tree together.
	// The previous two-step approach (update-ref + reset --hard HEAD) left
	// the index stale between steps, staging reversions of merged PR changes.
	m.gitCmd(m.ProjectDir, "reset", "--hard", "origin/"+defaultBranch)
	m.Logger.Log("Updated local %s to origin/%s", defaultBranch, defaultBranch)

	return true, nil
}

// mergeOpts returns the merge options for the current Manager configuration.
func (m *Manager) mergeOpts() MergeOpts {
	return MergeOpts{
		DeleteBranch: true,
		Admin:        m.MergeAdmin,
	}
}

// nwoFromRemote extracts "owner/repo" from a GitHub remote URL.
func nwoFromRemote(remoteURL string) string {
	// Handle SSH: git@github.com:owner/repo.git
	if idx := strings.Index(remoteURL, ":"); strings.HasPrefix(remoteURL, "git@") && idx > 0 {
		nwo := remoteURL[idx+1:]
		nwo = strings.TrimSuffix(nwo, ".git")
		return nwo
	}
	// Handle HTTPS: https://github.com/owner/repo.git
	parts := strings.Split(strings.TrimSuffix(remoteURL, ".git"), "/")
	if len(parts) >= 2 {
		return parts[len(parts)-2] + "/" + parts[len(parts)-1]
	}
	return ""
}

// ForcePush pushes the current branch to the remote with --force-with-lease,
// which is needed after rebasing to resolve merge conflicts on a PR.
func (m *Manager) ForcePush(ctx context.Context) error {
	if m.WorktreeBranch == "" {
		return nil
	}
	m.Logger.Log("Force-pushing %s...", m.WorktreeBranch)
	return m.gitCmdErrCtx(ctx, m.WorkDir, "push", "--force-with-lease", "origin", m.WorktreeBranch)
}

// MaxMergeAttempts is the total number of merge attempts including retries
// after conflict resolution and CI fixes.
const MaxMergeAttempts = 4

// MergeRetryOpts configures the merge-with-retry pipeline.
type MergeRetryOpts struct {
	// OnCIFailure is called when CI checks fail on the PR. It should attempt
	// to fix the failure (e.g. by spawning a fix agent) and return true if
	// the fix was applied and a retry should be attempted.
	OnCIFailure func(ciErr *CIFailureError) bool
}

// ResolveConflict rebases onto the default branch and force-pushes to
// resolve PR merge conflicts before the next merge attempt.
func (m *Manager) ResolveConflict(ctx context.Context) error {
	defaultBranch := m.detectDefaultBranch()
	m.Logger.Log("%s Rebasing onto %s to resolve merge conflicts...", logging.BranchTag(defaultBranch), defaultBranch)
	if err := m.RebaseOntoDefaultBranch(ctx); err != nil {
		return fmt.Errorf("conflict resolution rebase failed: %w", err)
	}
	m.Logger.Log("%s Force-pushing rebased branch...", logging.BranchTag(defaultBranch))
	return m.ForcePush(ctx)
}

// MergeWithRetry is the single merge pipeline: try merge, detect error type,
// handle it, retry. Conflicts trigger rebase + force-push; CI failures
// delegate to the OnCIFailure callback. Both share a single retry budget.
func (m *Manager) MergeWithRetry(ctx context.Context, opts MergeRetryOpts) (bool, error) {
	for attempt := 0; attempt < MaxMergeAttempts; attempt++ {
		merged, err := m.AutoMergeCurrentBranch(ctx)
		if err == nil {
			return merged, nil
		}

		if attempt > 0 {
			m.Logger.Warn("Merge attempt %d failed: %v", attempt+1, err)
		}

		var conflictErr *MergeConflictError
		if errors.As(err, &conflictErr) {
			if resolveErr := m.ResolveConflict(ctx); resolveErr != nil {
				return false, resolveErr
			}
			continue
		}

		var ciErr *CIFailureError
		if errors.As(err, &ciErr) {
			if opts.OnCIFailure != nil && opts.OnCIFailure(ciErr) {
				continue
			}
			return false, err
		}

		return false, err
	}
	return false, fmt.Errorf("merge failed after %d attempts", MaxMergeAttempts)
}

// FlushUnpushedWork pushes any unpushed commits and optionally squash-merges
// the PR. This is the safety net called before exiting or entering wait mode.
// PushAndCreatePR is idempotent (returns early when no commits ahead).
func (m *Manager) FlushUnpushedWork(ctx context.Context, taskID, taskDesc string, autoMerge bool) (merged bool, err error) {
	if pushErr := m.PushAndCreatePR(ctx, taskID, taskDesc); pushErr != nil {
		return false, pushErr
	}
	if !autoMerge {
		return false, nil
	}
	merged, err = m.AutoMergeCurrentBranch(ctx)
	if err != nil {
		return false, err
	}
	if merged {
		if resetErr := m.PostMergeReset(); resetErr != nil {
			return true, resetErr
		}
	}
	return merged, nil
}

// PostMergeReset force-resets the worktree to origin/main after a successful
// squash-merge. The old branch is disposable — all its work is already on
// main. Uses --force checkout and git clean to guarantee a pristine working
// tree with no leftover files from the previous task.
func (m *Manager) PostMergeReset() error {
	if m.WorktreeBranch == "" || m.WorkDir == m.ProjectDir {
		return nil
	}

	defaultBranch := m.detectDefaultBranch()
	oldBranch := m.WorktreeBranch
	newBranch := m.TempBranch()

	if err := m.gitCmdErr(m.WorkDir, "checkout", "--force", "-B", newBranch, "origin/"+defaultBranch); err != nil {
		return fmt.Errorf("post-merge reset: checkout failed: %w", err)
	}

	// Remove untracked files and directories left by the previous task.
	if err := m.gitCmdErr(m.WorkDir, "clean", "-fd"); err != nil {
		m.Logger.Warn("git clean failed (non-fatal): %v", err)
	}

	if oldBranch != newBranch {
		m.gitCmd(m.WorkDir, "branch", "-D", oldBranch)
	}

	m.WorktreeBranch = newBranch
	m.BranchRenamed = false
	if m.State != nil {
		_ = m.State.Write("worktree_branch", m.WorktreeBranch)
	}
	m.Logger.Log("%s Force-reset to %s", logging.BranchTag(defaultBranch), newBranch)
	return nil
}
