package git

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// formatPRBody assembles description, acceptance criteria, and agent
// summary into a structured PR body when all context is available.
// This used to be (l *Loop).prBody — moved here in Commit C2 because
// PR markdown formatting is git/github's protocol concern, not the
// orchestrator's.
func TestFormatPRBody_FullContext(t *testing.T) {
	body := formatPRBody(
		"Fix the auth middleware to validate tokens",
		"1. Tokens are validated\n2. Invalid tokens return 401",
		"Fixed auth middleware token validation",
	)

	if !strings.Contains(body, "## Description") {
		t.Error("body should contain Description section")
	}
	if !strings.Contains(body, "Fix the auth middleware") {
		t.Error("body should contain task description")
	}
	if !strings.Contains(body, "## Acceptance Criteria") {
		t.Error("body should contain Acceptance Criteria section")
	}
	if !strings.Contains(body, "Tokens are validated") {
		t.Error("body should contain acceptance criteria content")
	}
	if !strings.Contains(body, "## Summary") {
		t.Error("body should contain Summary section")
	}
	if !strings.Contains(body, "Fixed auth middleware") {
		t.Error("body should contain agent summary")
	}
}

// formatPRBody omits Description when no description is supplied but
// keeps Summary so the PR has at least the agent narrative.
func TestFormatPRBody_NoDescription(t *testing.T) {
	body := formatPRBody("", "", "Implemented the feature")

	if strings.Contains(body, "## Description") {
		t.Error("body should not contain Description when none supplied")
	}
	if !strings.Contains(body, "## Summary") {
		t.Error("body should contain Summary section as fallback")
	}
	if !strings.Contains(body, "Implemented the feature") {
		t.Error("body should contain agent summary")
	}
}

// formatPRBody returns an empty string when no context is supplied.
// Never produces generic "Automated PR for X" boilerplate.
func TestFormatPRBody_NoContext(t *testing.T) {
	body := formatPRBody("", "", "")
	if body != "" {
		t.Errorf("body should be empty when no context is available, got %q", body)
	}
}

// formatPRBody must never produce generic boilerplate that disguises
// the lack of useful task context.
func TestFormatPRBody_NeverGeneric(t *testing.T) {
	body := formatPRBody("Some task description", "", "completed task")

	if strings.Contains(body, "Automated PR for") {
		t.Error("body must not contain generic 'Automated PR for' text")
	}
	if strings.Contains(body, "Generated by ralph") {
		t.Error("body must not contain generic 'Generated by ralph' text")
	}
}

// MergePR with a 200 response signals a successful squash-merge.
func TestMergePR_HTTP200_ReturnsMerged(t *testing.T) {
	output := "HTTP/2.0 200 OK\r\n\r\n{}"
	result := classifyMergeStatus(output, nil)
	if !result.Merged {
		t.Errorf("expected Merged=true for HTTP 200, got %+v", result)
	}
	if result.Blocked || result.Conflict {
		t.Errorf("expected no Blocked/Conflict flags for HTTP 200, got %+v", result)
	}
}

// MergePR with a 405 response means branch protection is blocking the merge.
func TestMergePR_HTTP405_ReturnsBlocked(t *testing.T) {
	output := "HTTP/2.0 405 Method Not Allowed\r\n\r\n{\"message\":\"Pull Request is not mergeable\"}"
	result := classifyMergeStatus(output, fmt.Errorf("exit status 1"))
	if !result.Blocked {
		t.Errorf("expected Blocked=true for HTTP 405, got %+v", result)
	}
	if result.Merged || result.Conflict {
		t.Errorf("expected no Merged/Conflict flags for HTTP 405, got %+v", result)
	}
}

// MergePR with a 409 response means the PR has unresolvable merge conflicts.
func TestMergePR_HTTP409_ReturnsConflict(t *testing.T) {
	output := "HTTP/2.0 409 Conflict\r\n\r\n{\"message\":\"Merge conflict\"}"
	result := classifyMergeStatus(output, fmt.Errorf("exit status 1"))
	if !result.Conflict {
		t.Errorf("expected Conflict=true for HTTP 409, got %+v", result)
	}
	if result.Merged || result.Blocked {
		t.Errorf("expected no Merged/Blocked flags for HTTP 409, got %+v", result)
	}
}

// PRDiff uses gh api with the diff Accept header, not gh pr diff.
// A fake gh binary records the invocation args; the test verifies the
// implementation sends "gh api repos/{nwo}/pulls/{num}" with the diff header.
func TestPRDiff_UsesGhAPI(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	script := "#!/bin/sh\necho \"$@\" >> " + logFile + "\necho '+added line'\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	diff, err := g.PRDiff("https://github.com/owner/repo.git", 42)
	if err != nil {
		t.Fatalf("PRDiff returned error: %v", err)
	}
	if !strings.Contains(diff, "+added line") {
		t.Errorf("unexpected diff output: %q", diff)
	}

	raw, readErr := os.ReadFile(logFile)
	if readErr != nil {
		t.Fatalf("gh was never called: %v", readErr)
	}
	invocation := string(raw)

	if !strings.Contains(invocation, "api") {
		t.Errorf("expected 'gh api' invocation, got: %q", invocation)
	}
	if !strings.Contains(invocation, "repos/owner/repo/pulls/42") {
		t.Errorf("expected repos/owner/repo/pulls/42 in args, got: %q", invocation)
	}
	if !strings.Contains(invocation, "application/vnd.github.diff") {
		t.Errorf("expected application/vnd.github.diff Accept header, got: %q", invocation)
	}
	if strings.Contains(invocation, "pr diff") {
		t.Errorf("found 'gh pr diff' invocation — must use gh api: %q", invocation)
	}
}

// The stubGitHub type satisfies the GitHub interface, proving that test stubs
// can replace all GitHub CLI operations without shelling out.
func TestStubGitHub_SatisfiesInterface(t *testing.T) {
	var _ gitHub = &stubGitHub{}
}

// CreatePROpts carries all parameters in a single struct so callers avoid
// positional-parameter mistakes.
func TestCreatePROpts_FieldsPreserved(t *testing.T) {
	var captured CreatePROpts
	stub := &capturingGitHub{createPR: func(opts CreatePROpts) (int, error) {
		captured = opts
		return 42, nil
	}}

	opts := CreatePROpts{
		Head:  "feature-branch",
		Base:  "main",
		Title: "Add widget",
		Body:  "Automated PR",
		Repo:  "owner/repo",
		Dir:   "/tmp/work",
	}
	if _, err := stub.CreatePR(opts); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if captured != opts {
		t.Errorf("CreatePR opts not passed through:\ngot:  %+v\nwant: %+v", captured, opts)
	}
}

// GetRunLog returns the stub's configured RunLogValue, proving the interface
// method can be stubbed for CI failure log testing.
func TestGetRunLog_Stubbable(t *testing.T) {
	stub := newStubGitHub()
	if result := stub.GetRunLog(42, "/tmp"); result != "" {
		t.Errorf("expected empty string from default stub, got %q", result)
	}

	stub.RunLogValue = "error TS2307: Cannot find module './Missing'"
	if result := stub.GetRunLog(42, "/tmp"); result != stub.RunLogValue {
		t.Errorf("expected configured RunLogValue, got %q", result)
	}
}

// ListChecks replaces the former FetchChecks method, returning CI check results
// that callers use to determine merge readiness.
func TestListChecks_Stubbable(t *testing.T) {
	stub := newStubGitHub()
	stub.Checks = []CICheckResult{
		{Name: "build", State: "SUCCESS", Bucket: "pass"},
		{Name: "lint", State: "FAILURE", Bucket: "fail"},
	}

	checks, err := stub.ListChecks(99, "owner/repo")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(checks) != 2 {
		t.Fatalf("expected 2 checks, got %d", len(checks))
	}
	if checks[1].Name != "lint" {
		t.Errorf("expected second check name 'lint', got %q", checks[1].Name)
	}
}

// GetPR returns a PRDetail with all fields populated and a deterministic
// HeadSHA derived from the PR number.
func TestGetPR_ReturnsAllFields(t *testing.T) {
	stub := newStubGitHub()
	stub.PRHead = "feature-branch"
	stub.HeadSHA = "abc123"

	pr, err := stub.GetPR("owner/repo", 42)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if pr.State != "OPEN" {
		t.Errorf("state: want %q, got %q", "OPEN", pr.State)
	}
	if pr.BaseRef != "main" {
		t.Errorf("BaseRef: want %q, got %q", "main", pr.BaseRef)
	}
	if pr.HeadRef != "feature-branch" {
		t.Errorf("HeadRef: want %q, got %q", "feature-branch", pr.HeadRef)
	}
	if pr.HeadSHA != "abc123" {
		t.Errorf("HeadSHA: want %q, got %q", "abc123", pr.HeadSHA)
	}
}

// Manager.GetCIFailureLog delegates to the injected GitHub interface's GetRunLog,
// confirming that loop code can get CI logs without shelling out.
func TestManager_GetCIFailureLog_DelegatesToGitHub(t *testing.T) {
	stub := newStubGitHub()
	stub.RunLogValue = "test failure output line 1\nline 2"
	mgr := &Repo{
		baseBranch: "main",
		github: stub,
	}

	result := mgr.GetCIFailureLog(42)
	if result != "test failure output line 1\nline 2" {
		t.Errorf("expected delegated log output, got %q", result)
	}
}

// DetectActiveReviewers returns Copilot in the active list when the Copilot
// ruleset has review_on_push=true. The Copilot reviewer gets ReviewOnPush=true
// and retains the full 120s timeout. The /installations endpoint is never called.
func TestDetectActiveReviewers_CopilotWithReviewOnPush(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	listResponse := `[{"id":1,"name":"main","target":"branch","enforcement":"active"}]`
	detailResponse := `{"id":1,"name":"main","rules":[{"type":"copilot_code_review","parameters":{"review_on_push":true}}]}`
	script := "#!/bin/sh\n" +
		"echo \"$@\" >> " + logFile + "\n" +
		"case \"$@\" in\n" +
		"  *rulesets/1*) echo '" + detailResponse + "' ;;\n" +
		"  *rulesets*) echo '" + listResponse + "' ;;\n" +
		"  *) exit 1 ;;\n" +
		"esac\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{CopilotGatedTimeout: 120 * time.Second, CopilotOpportunisticTimeout: 90 * time.Second}
	reviewers, err := g.DetectActiveReviewers("owner/repo")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(reviewers) != 1 {
		t.Fatalf("expected 1 active reviewer, got %d", len(reviewers))
	}
	if reviewers[0].BotUsername != "copilot-pull-request-reviewer" {
		t.Errorf("expected copilot bot username, got %q", reviewers[0].BotUsername)
	}
	if !reviewers[0].ReviewOnPush {
		t.Error("expected ReviewOnPush=true when copilot_code_review ruleset has review_on_push=true")
	}
	if reviewers[0].DefaultTimeout != 120*time.Second {
		t.Errorf("expected 120s timeout when review_on_push=true, got %v", reviewers[0].DefaultTimeout)
	}

	raw, _ := os.ReadFile(logFile)
	log := string(raw)
	if strings.Contains(log, "installations") {
		t.Errorf("DetectActiveReviewers must not call /installations endpoint, got: %q", log)
	}
	if !strings.Contains(log, "repos/owner/repo/rulesets") {
		t.Errorf("expected rulesets endpoint call, got: %q", log)
	}
}

// DetectActiveReviewers sets ReviewOnPush=false and reduces timeout to 90s when
// the Copilot ruleset has review_on_push=false, since the review is opportunistic.
func TestDetectActiveReviewers_CopilotWithoutReviewOnPush(t *testing.T) {
	bin := t.TempDir()
	listResponse := `[{"id":1,"name":"main","target":"branch","enforcement":"active"}]`
	detailResponse := `{"id":1,"name":"main","rules":[{"type":"copilot_code_review","parameters":{"review_on_push":false}}]}`
	script := "#!/bin/sh\n" +
		"case \"$@\" in\n" +
		"  *rulesets/1*) echo '" + detailResponse + "' ;;\n" +
		"  *rulesets*) echo '" + listResponse + "' ;;\n" +
		"  *) exit 1 ;;\n" +
		"esac\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{CopilotGatedTimeout: 120 * time.Second, CopilotOpportunisticTimeout: 90 * time.Second}
	reviewers, err := g.DetectActiveReviewers("owner/repo")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(reviewers) != 1 {
		t.Fatalf("expected 1 active reviewer, got %d", len(reviewers))
	}
	if reviewers[0].ReviewOnPush {
		t.Error("expected ReviewOnPush=false when review_on_push=false in ruleset")
	}
	if reviewers[0].DefaultTimeout != 90*time.Second {
		t.Errorf("expected 90s timeout when review_on_push=false, got %v", reviewers[0].DefaultTimeout)
	}
}

// DetectActiveReviewers returns an empty list when no copilot_code_review ruleset
// exists, proving the loop skips polling when Copilot is not configured.
func TestDetectActiveReviewers_NoCopilotRuleset(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	listResponse := `[{"id":1,"name":"main","target":"branch","enforcement":"active"}]`
	detailResponse := `{"id":1,"name":"main","rules":[{"type":"required_status_checks","parameters":{}}]}`
	script := "#!/bin/sh\n" +
		"echo \"$@\" >> " + logFile + "\n" +
		"case \"$@\" in\n" +
		"  *rulesets/1*) echo '" + detailResponse + "' ;;\n" +
		"  *rulesets*) echo '" + listResponse + "' ;;\n" +
		"  *) exit 1 ;;\n" +
		"esac\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{CopilotGatedTimeout: 120 * time.Second, CopilotOpportunisticTimeout: 90 * time.Second}
	reviewers, err := g.DetectActiveReviewers("owner/repo")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(reviewers) != 0 {
		t.Errorf("expected 0 active reviewers when no copilot ruleset configured, got %d", len(reviewers))
	}
	raw, _ := os.ReadFile(logFile)
	if strings.Contains(string(raw), "installations") {
		t.Errorf("DetectActiveReviewers must not call /installations endpoint")
	}
}

// stubGitHub.DetectActiveReviewers returns the configured ActiveReviewers slice,
// proving tests can control the reviewer list without shelling out.
func TestStubGitHub_DetectActiveReviewers(t *testing.T) {
	stub := &stubGitHub{
		ActiveReviewers: []Reviewer{
			{AppSlug: "copilot-code-review", BotUsername: "copilot-pull-request-reviewer", DefaultTimeout: 120 * time.Second, ReviewOnPush: true},
		},
	}
	reviewers, err := stub.DetectActiveReviewers("owner/repo")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(reviewers) != 1 {
		t.Fatalf("expected 1 reviewer, got %d", len(reviewers))
	}
	if reviewers[0].BotUsername != "copilot-pull-request-reviewer" {
		t.Errorf("expected copilot bot, got %q", reviewers[0].BotUsername)
	}
	if !reviewers[0].ReviewOnPush {
		t.Error("expected ReviewOnPush=true from stub")
	}
}

// PollReview returns an AutoReview with body and inline comments when the given
// bot username has submitted a review on the PR.
func TestPollReview_ReturnsAutoReview(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")

	reviewJSON := `[{"id":1001,"user":{"login":"copilot-pull-request-reviewer"},"state":"COMMENTED","body":"LGTM with suggestions"}]`
	commentsJSON := `[{"path":"main.go","line":42,"body":"Consider using constants","pull_request_review_id":1001}]`
	script := "#!/bin/sh\necho \"$@\" >> " + logFile + "\nif echo \"$@\" | grep -q 'comments'; then\n  echo '" + commentsJSON + "'\nelse\n  echo '" + reviewJSON + "'\nfi\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	review, err := g.PollReview("owner/repo", "copilot-pull-request-reviewer", 42, 5*time.Second)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if review == nil {
		t.Fatal("expected non-nil review")
	}
	if review.Body != "LGTM with suggestions" {
		t.Errorf("Body: want %q, got %q", "LGTM with suggestions", review.Body)
	}
	if len(review.Comments) != 1 {
		t.Fatalf("expected 1 comment, got %d", len(review.Comments))
	}
	if review.Comments[0].Path != "main.go" {
		t.Errorf("Path: want main.go, got %q", review.Comments[0].Path)
	}
	if review.Comments[0].Line != 42 {
		t.Errorf("Line: want 42, got %d", review.Comments[0].Line)
	}
	if review.Comments[0].Body != "Consider using constants" {
		t.Errorf("Body: want %q, got %q", "Consider using constants", review.Comments[0].Body)
	}
}

// ListChecks uses gh api repos/{nwo}/commits/{sha}/check-runs instead of
// gh pr checks. It fetches the head SHA via GetPR and maps API status/conclusion
// fields to CICheckResult State and Bucket values that callers depend on.
func TestListChecks_UsesGhAPICheckRuns(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	checksJSON := `[{"name":"build","status":"completed","conclusion":"success","started_at":"2024-01-01T00:00:00Z"},{"name":"lint","status":"completed","conclusion":"failure","started_at":"2024-01-01T00:00:00Z"},{"name":"queue","status":"queued","conclusion":null,"started_at":null}]`
	script := "#!/bin/sh\necho \"$@\" >> " + logFile + "\n" +
		"if echo \"$@\" | grep -q 'check-runs'; then\n" +
		"  echo '" + checksJSON + "'\n" +
		"elif echo \"$@\" | grep -q 'pulls/42'; then\n" +
		"  printf 'OPEN\\tmain\\tfeature\\tabc123def\\n'\n" +
		"fi\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	checks, err := g.ListChecks(42, "https://github.com/owner/repo.git")
	if err != nil {
		t.Fatalf("ListChecks returned error: %v", err)
	}
	if len(checks) != 3 {
		t.Fatalf("expected 3 checks, got %d", len(checks))
	}

	raw, _ := os.ReadFile(logFile)
	invocations := string(raw)
	if strings.Contains(invocations, "pr checks") {
		t.Errorf("ListChecks must not use 'gh pr checks', got: %q", invocations)
	}
	if !strings.Contains(invocations, "check-runs") {
		t.Errorf("expected check-runs endpoint, got: %q", invocations)
	}
	if !strings.Contains(invocations, "abc123def") {
		t.Errorf("expected head SHA in check-runs URL, got: %q", invocations)
	}

	// completed+success → SUCCESS/pass
	if checks[0].Name != "build" || checks[0].State != "SUCCESS" || checks[0].Bucket != "pass" {
		t.Errorf("build: expected SUCCESS/pass, got State=%q Bucket=%q", checks[0].State, checks[0].Bucket)
	}
	// completed+failure → FAILURE/fail
	if checks[1].Name != "lint" || checks[1].State != "FAILURE" || checks[1].Bucket != "fail" {
		t.Errorf("lint: expected FAILURE/fail, got State=%q Bucket=%q", checks[1].State, checks[1].Bucket)
	}
	// queued → PENDING/pending
	if checks[2].Name != "queue" || checks[2].State != "PENDING" || checks[2].Bucket != "pending" {
		t.Errorf("queue: expected PENDING/pending, got State=%q Bucket=%q", checks[2].State, checks[2].Bucket)
	}
}

// mapCheckRun maps GitHub API check-run conclusion strings to the
// State/Bucket values that evaluateChecks uses for merge-gating decisions.
func TestMapCheckRun_ConclusionMapping(t *testing.T) {
	cases := []struct {
		conclusion    string
		wantState     string
		wantBucket    string
	}{
		{"success", "SUCCESS", "pass"},
		{"neutral", "SUCCESS", "pass"},
		{"skipped", "SUCCESS", "pass"},
		{"failure", "FAILURE", "fail"},
		{"timed_out", "FAILURE", "fail"},
		{"action_required", "FAILURE", "fail"},
		{"cancelled", "FAILURE", "fail"},
		{"startup_failure", "FAILURE", "fail"},
		{"stale", "FAILURE", "fail"},
		{"unknown_future_conclusion", "PENDING", "pending"},
	}
	for _, tc := range cases {
		c := tc.conclusion
		result := mapCheckRun("check", "completed", &c, nil)
		if result.State != tc.wantState || result.Bucket != tc.wantBucket {
			t.Errorf("conclusion=%q: want State=%q Bucket=%q, got State=%q Bucket=%q",
				tc.conclusion, tc.wantState, tc.wantBucket, result.State, result.Bucket)
		}
	}
	// nil conclusion (pending/queued check) → PENDING
	result := mapCheckRun("check", "completed", nil, nil)
	if result.State != "PENDING" || result.Bucket != "pending" {
		t.Errorf("completed+nil conclusion: want PENDING/pending, got State=%q Bucket=%q", result.State, result.Bucket)
	}
	// non-completed status always → PENDING regardless of conclusion
	s := "success"
	result = mapCheckRun("check", "queued", &s, nil)
	if result.State != "PENDING" || result.Bucket != "pending" {
		t.Errorf("queued+success: want PENDING/pending, got State=%q Bucket=%q", result.State, result.Bucket)
	}
}

// MergePR uses gh api PUT repos/{nwo}/pulls/{num}/merge — never gh pr merge --admin.
// A 405 response returns Blocked without any retry, respecting branch protection.
func TestMergePR_HTTP405_ReturnsBlocked_NoAdminRetry(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	script := "#!/bin/sh\necho \"$@\" >> " + logFile + "\necho 'HTTP/2.0 405 Method Not Allowed'\necho ''\necho '{\"message\":\"Branch protection\"}\n'\nexit 1\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	result := g.MergePR(42, "https://github.com/owner/repo.git", MergeOpts{})
	if result.Merged {
		t.Error("expected Merged=false when branch protection blocks merge")
	}
	if !result.Blocked {
		t.Error("expected Blocked=true for HTTP 405 response")
	}

	raw, err := os.ReadFile(logFile)
	if err != nil {
		t.Fatalf("reading gh invocation log: %v", err)
	}
	// Only one gh invocation — no admin retry after 405.
	invocations := strings.Count(string(raw), "pulls/42/merge")
	if invocations != 1 {
		t.Errorf("expected exactly 1 merge attempt (no admin retry), got %d", invocations)
	}
}

// EditPR uses gh api PATCH repos/{nwo}/pulls/{num} with title and body fields,
// not gh pr edit, so PR updates go through the REST API.
func TestEditPR_UsesGhAPI(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	script := "#!/bin/sh\necho \"$@\" >> " + logFile + "\necho '{}'\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	err := g.EditPR(42, "https://github.com/owner/repo.git", "New Title", "New body")
	if err != nil {
		t.Fatalf("EditPR returned error: %v", err)
	}

	raw, err := os.ReadFile(logFile)
	if err != nil {
		t.Fatalf("reading gh invocation log: %v", err)
	}
	invocation := string(raw)

	if strings.Contains(invocation, "pr edit") {
		t.Errorf("EditPR must not use 'gh pr edit', got: %q", invocation)
	}
	if !strings.Contains(invocation, "api") {
		t.Errorf("expected 'gh api' invocation, got: %q", invocation)
	}
	if !strings.Contains(invocation, "PATCH") {
		t.Errorf("expected PATCH method, got: %q", invocation)
	}
	if !strings.Contains(invocation, "repos/owner/repo/pulls/42") {
		t.Errorf("expected repos/owner/repo/pulls/42 endpoint, got: %q", invocation)
	}
	if !strings.Contains(invocation, "New Title") {
		t.Errorf("expected title in args, got: %q", invocation)
	}
	if !strings.Contains(invocation, "New body") {
		t.Errorf("expected body in args, got: %q", invocation)
	}
}

// ReopenPR uses gh api PATCH repos/{nwo}/pulls/{num} -f state=open,
// not gh pr reopen, so PR state changes go through the REST API.
func TestReopenPR_UsesGhAPI(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	script := "#!/bin/sh\necho \"$@\" >> " + logFile + "\necho '{}'\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	err := g.ReopenPR(42, "https://github.com/owner/repo.git")
	if err != nil {
		t.Fatalf("ReopenPR returned error: %v", err)
	}

	raw, _ := os.ReadFile(logFile)
	invocation := string(raw)

	if strings.Contains(invocation, "pr reopen") {
		t.Errorf("ReopenPR must not use 'gh pr reopen', got: %q", invocation)
	}
	if !strings.Contains(invocation, "api") {
		t.Errorf("expected 'gh api' invocation, got: %q", invocation)
	}
	if !strings.Contains(invocation, "PATCH") {
		t.Errorf("expected PATCH method, got: %q", invocation)
	}
	if !strings.Contains(invocation, "repos/owner/repo/pulls/42") {
		t.Errorf("expected repos/owner/repo/pulls/42 endpoint, got: %q", invocation)
	}
	if !strings.Contains(invocation, "state=open") {
		t.Errorf("expected state=open in args, got: %q", invocation)
	}
}

// ListOpenPRBranches uses gh api repos/{nwo}/pulls?state=open instead of
// gh pr list, returning branch names for all open PRs.
func TestListOpenPRBranches_UsesGhAPI(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	// The fake gh binary returns ref names as if --jq ".[].head.ref" ran.
	script := "#!/bin/sh\necho \"$@\" >> " + logFile + "\nprintf 'feature-a\\nfeature-b\\n'\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	branches, err := g.ListOpenPRBranches("https://github.com/owner/repo.git")
	if err != nil {
		t.Fatalf("ListOpenPRBranches returned error: %v", err)
	}
	if len(branches) != 2 {
		t.Fatalf("expected 2 branches, got %d: %v", len(branches), branches)
	}
	if branches[0] != "feature-a" || branches[1] != "feature-b" {
		t.Errorf("unexpected branches: %v", branches)
	}

	raw, _ := os.ReadFile(logFile)
	invocation := string(raw)
	if strings.Contains(invocation, "pr list") {
		t.Errorf("ListOpenPRBranches must not use 'gh pr list', got: %q", invocation)
	}
	if !strings.Contains(invocation, "api") {
		t.Errorf("expected 'gh api' invocation, got: %q", invocation)
	}
	if !strings.Contains(invocation, "repos/owner/repo/pulls") {
		t.Errorf("expected repos/owner/repo/pulls endpoint, got: %q", invocation)
	}
	if !strings.Contains(invocation, "state=open") {
		t.Errorf("expected state=open param, got: %q", invocation)
	}
	if !strings.Contains(invocation, "--paginate") {
		t.Errorf("expected --paginate flag for pagination, got: %q", invocation)
	}
}

// ListAllPRs uses gh api repos/{nwo}/pulls?state=all instead of gh pr list,
// returning PRInfo structs with state normalized to uppercase.
func TestListAllPRs_UsesGhAPI(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	// NDJSON output: one object per line, as produced by --paginate --jq '.[]'
	pullsNDJSON := `{"number":10,"head":{"ref":"feat-a"},"base":{"ref":"main"},"state":"open","merged_at":null}
{"number":11,"head":{"ref":"feat-b"},"base":{"ref":"main"},"state":"closed","merged_at":null}
{"number":12,"head":{"ref":"feat-c"},"base":{"ref":"main"},"state":"closed","merged_at":"2024-01-01T00:00:00Z"}`
	gitPath := filepath.Join(bin, "git")
	gitScript := "#!/bin/sh\necho 'https://github.com/owner/repo.git'\n"
	if err := os.WriteFile(gitPath, []byte(gitScript), 0o755); err != nil {
		t.Fatal(err)
	}
	ghPath := filepath.Join(bin, "gh")
	ghScript := "#!/bin/sh\necho \"$@\" >> " + logFile + "\nprintf '" + pullsNDJSON + "\\n'\n"
	if err := os.WriteFile(ghPath, []byte(ghScript), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	prs, err := g.ListAllPRs(bin)
	if err != nil {
		t.Fatalf("ListAllPRs returned error: %v", err)
	}
	if len(prs) != 3 {
		t.Fatalf("expected 3 PRs, got %d", len(prs))
	}

	raw, _ := os.ReadFile(logFile)
	invocation := string(raw)
	if strings.Contains(invocation, "pr list") {
		t.Errorf("ListAllPRs must not use 'gh pr list', got: %q", invocation)
	}
	if !strings.Contains(invocation, "api") {
		t.Errorf("expected 'gh api' invocation, got: %q", invocation)
	}
	if !strings.Contains(invocation, "repos/owner/repo/pulls") {
		t.Errorf("expected repos/owner/repo/pulls endpoint, got: %q", invocation)
	}
	if !strings.Contains(invocation, "state=all") {
		t.Errorf("expected state=all param, got: %q", invocation)
	}
	if !strings.Contains(invocation, "--paginate") {
		t.Errorf("expected --paginate flag for pagination, got: %q", invocation)
	}

	// State is normalized to uppercase regardless of API's lowercase output.
	// merged_at:null is treated as not merged (OPEN/CLOSED preserved).
	if prs[0].State != PRStateOpen {
		t.Errorf("PR #10: expected state OPEN, got %q", prs[0].State)
	}
	if prs[1].State != PRStateClosed {
		t.Errorf("PR #11: expected state CLOSED (merged_at:null), got %q", prs[1].State)
	}
	if prs[2].State != PRStateMerged {
		t.Errorf("PR #12: expected state MERGED (merged_at set), got %q", prs[2].State)
	}
}

// ListAllPRs paginates through all results so repos with >100 PRs return
// all items without silent truncation.
func TestListAllPRs_Paginates(t *testing.T) {
	bin := t.TempDir()
	// Simulate 101 PRs returned as NDJSON (as produced by --paginate --jq '.[]').
	var lines []string
	for i := 1; i <= 101; i++ {
		lines = append(lines, fmt.Sprintf(`{"number":%d,"head":{"ref":"branch-%d"},"base":{"ref":"main"},"state":"open","merged_at":null}`, i, i))
	}
	ndjson := strings.Join(lines, "\n")
	gitScript := "#!/bin/sh\necho 'https://github.com/owner/repo.git'\n"
	gitPath := filepath.Join(bin, "git")
	if err := os.WriteFile(gitPath, []byte(gitScript), 0o755); err != nil {
		t.Fatal(err)
	}
	ghScript := "#!/bin/sh\nprintf '" + ndjson + "\\n'\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(ghScript), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	prs, err := g.ListAllPRs(bin)
	if err != nil {
		t.Fatalf("ListAllPRs returned error: %v", err)
	}
	if len(prs) != 101 {
		t.Fatalf("expected 101 PRs (no truncation at 100), got %d", len(prs))
	}
}

// ListOpenPRBranches paginates through all results so repos with >100 open
// PRs return all branch names without silent truncation.
func TestListOpenPRBranches_Paginates(t *testing.T) {
	bin := t.TempDir()
	// Simulate 101 branch names returned (as produced by --paginate --jq '.[].head.ref').
	var branchLines []string
	for i := 1; i <= 101; i++ {
		branchLines = append(branchLines, fmt.Sprintf("branch-%d", i))
	}
	output := strings.Join(branchLines, "\n")
	ghScript := "#!/bin/sh\nprintf '" + output + "\\n'\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(ghScript), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	branches, err := g.ListOpenPRBranches("https://github.com/owner/repo.git")
	if err != nil {
		t.Fatalf("ListOpenPRBranches returned error: %v", err)
	}
	if len(branches) != 101 {
		t.Fatalf("expected 101 branches (no truncation at 100), got %d", len(branches))
	}
}

// SearchPR uses gh api search/issues instead of gh pr list --search,
// finding a PR by task ID and returning its number.
func TestSearchPR_UsesGhAPI(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	gitPath := filepath.Join(bin, "git")
	gitScript := "#!/bin/sh\necho 'https://github.com/owner/repo.git'\n"
	if err := os.WriteFile(gitPath, []byte(gitScript), 0o755); err != nil {
		t.Fatal(err)
	}
	ghPath := filepath.Join(bin, "gh")
	// The fake gh binary returns the number as if --jq ".items[0].number // empty" ran.
	ghScript := "#!/bin/sh\necho \"$@\" >> " + logFile + "\necho '42'\n"
	if err := os.WriteFile(ghPath, []byte(ghScript), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	prNumber, err := g.SearchPR(bin, "my-task-id")
	if err != nil {
		t.Fatalf("SearchPR returned error: %v", err)
	}
	if prNumber != 42 {
		t.Errorf("expected PR number 42, got %d", prNumber)
	}

	raw, _ := os.ReadFile(logFile)
	invocation := string(raw)
	if strings.Contains(invocation, "pr list") {
		t.Errorf("SearchPR must not use 'gh pr list', got: %q", invocation)
	}
	if !strings.Contains(invocation, "api") {
		t.Errorf("expected 'gh api' invocation, got: %q", invocation)
	}
	if !strings.Contains(invocation, "search/issues") {
		t.Errorf("expected search/issues endpoint, got: %q", invocation)
	}
	if !strings.Contains(invocation, "my-task-id") {
		t.Errorf("expected query in args, got: %q", invocation)
	}
}

// PollReview returns nil without error when the timeout expires and no review
// from the given bot username has arrived, so the loop proceeds to merge.
func TestPollReview_Timeout_ReturnsNil(t *testing.T) {
	bin := t.TempDir()
	script := "#!/bin/sh\n" +
		"if echo \"$@\" | grep -q 'requested_reviewers'; then\n" +
		"  echo '{\"users\":[{\"login\":\"copilot-pull-request-reviewer\"}],\"teams\":[]}'\n" +
		"else\n" +
		"  echo '[{\"id\":999,\"user\":{\"login\":\"other-bot\"},\"state\":\"COMMENTED\",\"body\":\"not our reviewer\"}]'\n" +
		"fi\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	review, err := g.PollReview("owner/repo", "copilot-pull-request-reviewer", 42, 1*time.Millisecond)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if review != nil {
		t.Errorf("expected nil review on timeout, got %+v", review)
	}
}

// PollReview returns nil immediately (without entering the poll loop) when the
// bot is not in the PR's requested_reviewers list and has no existing review —
// polling would be wasted since no review is coming.
func TestPollReview_NotRequested_ReturnsNilImmediately(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	script := "#!/bin/sh\n" +
		"echo \"$@\" >> " + logFile + "\n" +
		"if echo \"$@\" | grep -q 'requested_reviewers'; then\n" +
		"  echo '{\"users\":[],\"teams\":[]}'\n" +
		"else\n" +
		"  echo '[]'\n" +
		"fi\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	// Long timeout — if pre-check works, returns nil immediately without waiting.
	review, err := g.PollReview("owner/repo", "copilot-pull-request-reviewer", 42, 60*time.Second)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if review != nil {
		t.Errorf("expected nil when bot not assigned, got %+v", review)
	}

	raw, _ := os.ReadFile(logFile)
	lines := strings.Split(strings.TrimSpace(string(raw)), "\n")
	var reviewCalls, requestedCalls int
	for _, line := range lines {
		if strings.Contains(line, "requested_reviewers") {
			requestedCalls++
		} else if strings.Contains(line, "reviews") {
			reviewCalls++
		}
	}
	if requestedCalls != 1 {
		t.Errorf("expected 1 requested_reviewers call, got %d", requestedCalls)
	}
	// At most 1 reviews check (initial pre-check), not a polling loop.
	if reviewCalls > 1 {
		t.Errorf("expected at most 1 reviews call before skipping, got %d", reviewCalls)
	}
}

// PollReview keeps polling when the bot's review state is PENDING (review not yet
// submitted) and returns the review once it reaches a terminal state like APPROVED.
func TestPollReview_PendingStateKeepsPolling(t *testing.T) {
	bin := t.TempDir()
	counterFile := filepath.Join(bin, "count")
	script := "#!/bin/sh\n" +
		"if echo \"$@\" | grep -q 'requested_reviewers'; then\n" +
		"  echo '{\"users\":[{\"login\":\"copilot-pull-request-reviewer\"}],\"teams\":[]}'\n" +
		"elif echo \"$@\" | grep -q 'comments'; then\n" +
		"  echo '[]'\n" +
		"else\n" +
		"  n=0\n" +
		"  [ -f " + counterFile + " ] && n=$(cat " + counterFile + ")\n" +
		"  n=$((n+1))\n" +
		"  echo $n > " + counterFile + "\n" +
		"  if [ \"$n\" -le 1 ]; then\n" +
		"    echo '[{\"id\":1,\"user\":{\"login\":\"copilot-pull-request-reviewer\"},\"state\":\"PENDING\",\"body\":\"\"}]'\n" +
		"  else\n" +
		"    echo '[{\"id\":1,\"user\":{\"login\":\"copilot-pull-request-reviewer\"},\"state\":\"APPROVED\",\"body\":\"LGTM\"}]'\n" +
		"  fi\n" +
		"fi\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	review, err := g.PollReview("owner/repo", "copilot-pull-request-reviewer", 42, 200*time.Millisecond)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if review == nil {
		t.Fatal("expected review after PENDING → APPROVED transition, got nil")
	}
	if review.Body != "LGTM" {
		t.Errorf("expected body %q, got %q", "LGTM", review.Body)
	}
}

// PollReview returns an AutoReview with an empty (non-nil) Comments slice when the
// bot submits an APPROVED review with no inline comments — state=APPROVED is terminal.
func TestPollReview_TerminalStateNoComments(t *testing.T) {
	bin := t.TempDir()
	script := "#!/bin/sh\n" +
		"if echo \"$@\" | grep -q 'requested_reviewers'; then\n" +
		"  echo '{\"users\":[{\"login\":\"copilot-pull-request-reviewer\"}],\"teams\":[]}'\n" +
		"elif echo \"$@\" | grep -q 'comments'; then\n" +
		"  echo '[]'\n" +
		"else\n" +
		"  echo '[{\"id\":1,\"user\":{\"login\":\"copilot-pull-request-reviewer\"},\"state\":\"APPROVED\",\"body\":\"\"}]'\n" +
		"fi\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	review, err := g.PollReview("owner/repo", "copilot-pull-request-reviewer", 42, 5*time.Second)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if review == nil {
		t.Fatal("expected non-nil AutoReview for APPROVED state with no comments")
	}
	if review.Comments == nil {
		t.Error("expected empty slice for Comments, not nil")
	}
	if len(review.Comments) != 0 {
		t.Errorf("expected 0 comments, got %d", len(review.Comments))
	}
}

// CreatePRViaAPI sends a valid JSON body even when title or body contain
// newlines, tabs, backslashes, backticks, and Unicode — characters where
// Go's %q formatting diverges from JSON encoding, causing GitHub 400 errors.
// FindOpenPR uses gh pr list --head {branch} --repo {nwo} instead of the
// gh api pulls endpoint with an owner:branch head filter, which GitHub's list
// API returns empty for even when the PR exists.
func TestFindOpenPR_UsesPRListNotAPIFilter(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	script := "#!/bin/sh\necho \"$@\" >> " + logFile + "\nprintf '42\\n'\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	prNum, err := g.FindOpenPR("ralph/my-task-branch", "https://github.com/owner/repo.git")
	if err != nil {
		t.Fatalf("FindOpenPR returned error: %v", err)
	}
	if prNum != 42 {
		t.Errorf("expected PR number 42, got %d", prNum)
	}

	raw, _ := os.ReadFile(logFile)
	invocation := string(raw)

	if !strings.Contains(invocation, "pr list") {
		t.Errorf("FindOpenPR must use 'gh pr list', got: %q", invocation)
	}
	if strings.Contains(invocation, "owner:") {
		t.Errorf("FindOpenPR must not use owner:branch head filter, got: %q", invocation)
	}
	if !strings.Contains(invocation, "--head") {
		t.Errorf("expected --head flag, got: %q", invocation)
	}
	if !strings.Contains(invocation, "ralph/my-task-branch") {
		t.Errorf("expected branch name in args, got: %q", invocation)
	}
	if !strings.Contains(invocation, "owner/repo") {
		t.Errorf("expected repo nwo in args, got: %q", invocation)
	}
}

// FindPR (all-states variant) uses gh pr list --state all instead of the
// gh api pulls endpoint with owner:branch filter.
func TestFindPR_UsesPRListNotAPIFilter(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	script := "#!/bin/sh\necho \"$@\" >> " + logFile + "\nprintf '77\\tFix auth\\thttps://github.com/owner/repo/pull/77\\n'\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	num, title, url, err := g.FindPR("ralph/my-task-branch", "https://github.com/owner/repo.git")
	if err != nil {
		t.Fatalf("FindPR returned error: %v", err)
	}
	if num != 77 {
		t.Errorf("expected PR number 77, got %d", num)
	}
	if title != "Fix auth" {
		t.Errorf("expected title 'Fix auth', got %q", title)
	}
	if url != "https://github.com/owner/repo/pull/77" {
		t.Errorf("unexpected url: %q", url)
	}

	raw, _ := os.ReadFile(logFile)
	invocation := string(raw)

	if !strings.Contains(invocation, "pr list") {
		t.Errorf("FindPR must use 'gh pr list', got: %q", invocation)
	}
	if strings.Contains(invocation, "owner:") {
		t.Errorf("FindPR must not use owner:branch head filter, got: %q", invocation)
	}
	if !strings.Contains(invocation, "--state") || !strings.Contains(invocation, "all") {
		t.Errorf("expected --state all, got: %q", invocation)
	}
}

// CreatePRViaAPI recovers from a 422 'already exists' error by looking up
// the existing open PR and returning its number instead of failing with 0.
func TestCreatePRViaAPI_Returns422ExistingPR(t *testing.T) {
	bin := t.TempDir()
	logFile := filepath.Join(bin, "gh.log")
	// First call (POST) exits 1 with a 422 "already exists" body.
	// Second call (pr list) succeeds and returns the existing PR number.
	script := `#!/bin/sh
echo "$@" >> ` + logFile + `
if echo "$@" | grep -q "pr list"; then
  printf '55\n'
  exit 0
fi
printf '{"message":"Validation Failed","errors":[{"message":"A pull request already exists for owner:ralph/my-branch."}]}\n'
exit 1
`
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	opts := CreatePROpts{
		Head: "ralph/my-branch",
		Base: "main",
		Repo: "https://github.com/owner/repo.git",
	}
	prNum, err := g.CreatePRViaAPI("owner/repo", opts)
	if err != nil {
		t.Fatalf("CreatePRViaAPI returned error on 422: %v", err)
	}
	if prNum != 55 {
		t.Errorf("expected existing PR number 55, got %d", prNum)
	}
}

func TestCreatePRViaAPI_SpecialCharsProduceValidJSON(t *testing.T) {
	bin := t.TempDir()
	stdinFile := filepath.Join(bin, "stdin.json")
	script := "#!/bin/sh\ncat > " + stdinFile + "\necho '{\"number\":99}'\n"
	ghPath := filepath.Join(bin, "gh")
	if err := os.WriteFile(ghPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+":"+os.Getenv("PATH"))

	g := &ghCLI{}
	opts := CreatePROpts{
		Title: "Fix `backtick` and \"quotes\"",
		Body:  "Line one\nLine two\tTabbed\nBackslash: \\\nUnicode: \u00e9",
		Head:  "feature/my-branch",
		Base:  "main",
	}
	prNum, err := g.CreatePRViaAPI("owner/repo", opts)
	if err != nil {
		t.Fatalf("CreatePRViaAPI returned error: %v", err)
	}
	if prNum != 99 {
		t.Errorf("expected PR number 99, got %d", prNum)
	}

	raw, readErr := os.ReadFile(stdinFile)
	if readErr != nil {
		t.Fatalf("gh was never called or stdin not captured: %v", readErr)
	}

	var parsed map[string]string
	if err := json.Unmarshal(raw, &parsed); err != nil {
		t.Fatalf("request body is not valid JSON: %v\nbody: %s", err, raw)
	}
	if parsed["title"] != opts.Title {
		t.Errorf("title mismatch: got %q, want %q", parsed["title"], opts.Title)
	}
	if parsed["body"] != opts.Body {
		t.Errorf("body mismatch: got %q, want %q", parsed["body"], opts.Body)
	}
}

